### ISSUE TITLE
Half redwood tree on chunk boundary

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1047]
**Game Version:** 1.15.0-pre6
**Platform:** Windows 
**Modded:** No 

### Description
Found a line of splited redwood trees, on a chunk boundary. The chunk wireframe is visible on the screenshot.

### How to reproduce
You can try with world seed 1533846596 starting climate "warm" and tp to -255 110 254, but there is no guarantee that the tree placement will be the same.

### Screenshots
![2021-06-22_10-50-44](https://user-images.githubusercontent.com/84909583/122896138-10088800-d349-11eb-8c61-746fc3a2fd45.png)

**Comment by Craluminum2413** [comment]
Trees aren't seed-deterministic

**Comment by Saricane** [comment]
That's why it's a little more difficult to reproduce the bug.

**Comment by radfast** [comment]
Thanks for reporting.  I cannot reproduce this in various testing.

Is it possible you used the `/wgen regen` command at all?   That will create half-trees, because it only updated chunks in (e.g. ) a 5x5 radius, and it makes new trees with a different RNG in the new chunks, therefore any tree in an old or new chunk which is half across the chunk boundary, would have this issue.   And actually it's not just redwoods, it would be half of any tree, for example the leafy canopy could be cut off in a straight line.  (Easier to see on redwoods though, because of the look of a trunk cut in half).

It cannot be the worldgen/treegen code itself, that would not be capable of producing an exactly straight edge like this on the chunk boundary.   (Trees always generate across chunk boundaries OK, otherwise you would see problems with every tree species in the game....)

Final possibility:  if the world - parts of this region - was originally generated in `pre.1` then there were known redwood bugs in that, but those were fixed from `pre.2` onwards...

**Comment by copygirl** [comment]
Will close as not reproducible for now. More information is welcome if this still occurs.
