### ISSUE TITLE
.charsel not saving updates on TOPTS

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1092]
**Game Version:** 1.15, appropx pre 8, TOPTS
**Platform:** Windows 10
**Modded:** No

### Description
With 1.15 many players wanted to select a new character voice instead of the default one.
Multiple people were reporting that .charsel does not work for them even after admin allowed it.
SplitUltimatum and Aphelion tried and it did not work.
I also tried, iirc I probably never used this command before, so supposed to have 1 free change (?).
It shown me the dialog, allowed to select evrything, but when I clicked save, my appearance and voice left as they were, even after relog.

Another issue is that game shows me the dialog, allows to select and save. If I do not have permissions for this, it should explicitly say this, instead letting me waste my time on changes and then discarding them.
I can use .charsel more times and it always shows me the dialog.

Testing this requires admin involvement so I can't test it thoroghly.

### How to reproduce
1. Type .charsel command, either after admin allowed it or when you never used it before.
2. Update your appearance and voice, Save.
3. Your look and voice actually not changed.

### Expected behavior
1. When player is allowed to use .charsel, changed should be properly saved, updating their voice and appearance.
2. When player has no permissions to use .charsel, no dialog of character and class selection should appear.

### Screenshots
--

### Logs
--

**Comment by Heptagon-ru** [comment]
Tested on TOPTS , 1.15 rc1, on two persons - it works.

So the only part of the issue not resolved is - showing the .charsel dialog and letting to fake save when player actually have no permission to to do it already. Still happening, tested after the successful change allowed by admin.

If this last part is too minor, you can close the ticket.

**Comment by copygirl** [comment]
I'll leave it up, even with the same priority. I think if people get told they can use `.charsel` and they find it not working (even if it is because they were not given permission before) they'll be confused and think it's a bug. Especially after a big update when players may want to change their characters.

Perhaps it's time to change `charsel` to a server command, that will then send an internal message to the client that either shows a dialog saying they can only change characters once (and need permission to do so again), or successfully shows the dialog. What even causes the dialog to be shown initially when you first join a world? That could be reused. Maybe #277 could be implemented for it it at the same time?

**Comment by Th3Dilli** [comment]
now properly fixed with client side error if the user does not have permission to change the character
