### ISSUE TITLE
Vintage Story 1.15-pre.12 Crashing on Startup on MacOS Catalina 10.15

### ISSUE THREAD

**Issue by hatcomGH** [anegostudios/VintageStory-Issues#1106]
**Game Version:** 1.15-pre.12
**Platform:** MacOS Catalina 10.15 
**Modded:** No 

### Description
Game is crashing instantly.

### How to reproduce
Open the game on MacOS Catalina 10.15, I would assume. Not sure if I have anything missing that the game needs.

### Logs
Logs have been uploaded here: https://gist.github.com/hatcomGH/db392cf412b265a3c99cf2178f0b3d16

**Comment by copygirl** [comment]
Unsure if the developers can look into this right away, as they don't often have the hardware to debug the issue on. Another player (#983) on Mac can get into the game, but the HUD elements disappear when looking at a block. Due to Apple's decision to stop supporting OpenGL, it might be hard to continue supporting the game for Mac.

(If this issue can't be solved and you're looking for a refund, open a support ticket on the website. The developers are very open to giving refunds for any reason, but obviously especially when players run into issues that prevent them from playing the game altogether.)

**Comment by copygirl** [comment]
Here's a post on the forums by Tyron on the matter:

[Dropping (official) Mac OS Support](https://www.vintagestory.at/forums/topic/2386-dropping-official-mac-os-support/)

**Comment by hatcomGH** [comment]
Ah, ok. Not a problem. I'll be getting a Windows computer soon anyway. Glad I can still play this game eventually!
