### ISSUE TITLE
`Max FPS` setting doesn't work properly

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1133]
**Game Version:** 1.15.0-rc.2
**Platform:** Windows
**Modded:** No

### Description
When the "Max FPS" setting is set to, for example, 60 fps, this limits framerate to 35 fps, but never to 60 fps.
My setup: i5-7400, GTX1050Ti, 16 GB of RAM

### Videos

https://user-images.githubusercontent.com/69315569/125179884-e29e5400-e1fb-11eb-9306-ff2a2a2cf645.mp4

**Comment by Craluminum2413** [comment]
Also, my friend had the same on his computer (RTX2060 SUPER, Ryzen 5 2600, 16 GB of RAM). Exactly this setting ruined his impression about optimization of the game, although he was wrong

**Comment by tyronx** [comment]
The explanation for this is in your video - I'll color the 'please note' part in orange. 

![nvidia](https://user-images.githubusercontent.com/762006/125192067-77ca3880-e24e-11eb-8453-d7871b6b1354.jpg)

**Comment by Craluminum2413** [comment]
Ok, I'll will always set this setting to"Unlimited"

**Comment by tyronx** [comment]
Oh and the advice is wrong. "Application controlled" doesn't seem to work, you have to specifically turn vsync on or off in the nvidia settings. I will correct the text.

**Comment by Craluminum2413** [comment]
Also my monitor doesn't support VSync, but does FreeSync
![image](https://user-images.githubusercontent.com/69315569/125192207-469e3800-e24f-11eb-959d-10f0cfbd4467.png)

**Comment by tyronx** [comment]
VSync is not specific to monitors. 

You are mixing it up with GSync&FreeSync, which does require monitor support.

**Comment by Craluminum2413** [comment]
I still can't figure out why this setting behaves this way

**Comment by tyronx** [comment]
hm, interesting. Not sure why that is the case.

**Comment by radfast** [comment]
I think the tooltip is the wrong way round, the "might cause half FPS (e.g. 30 instead of 60)" is what is manifesting here, and that should also be written on the VSync: off setting.

The technical reason this occurs is related to the Windows system timer, which by default has a granularity of 15.6667 ms i.e. 1/64 second, and sometimes "misses" and gives us 1/32 second of waiting.  So you are probably seeing 32fps if you look closely.

**Comment by radfast** [comment]
I'll make a tweak that should reduce this effect in rc3

**Comment by tyronx** [comment]
@radfast please discuss this tweak with me before committing. The game loops is a *very* sensitive bit of code

**Comment by Craluminum2413** [comment]
Well, I'm still getting 30 fps when fps is set to 60 fps

https://user-images.githubusercontent.com/69315569/125513596-b6cdbec9-d6a1-4246-a552-e52bc4c502a5.mp4

**Comment by radfast** [comment]
@Craluminum2413: Out of interest was this improved for you in 1.15.0 stable?

**Comment by Craluminum2413** [comment]
Nope, still the same. Sometimes 'average fps' can go up to 40-50 fps, but the minimum fps is still 30

**Comment by radfast** [comment]
What happens if you set MaxFPS to 65, as suggested on the [wiki](https://wiki.vintagestory.at/index.php?title=Framerate_and_Performance#Balancing_performance.2C_temperature_and_power_consumption)?

**Comment by Craluminum2413** [comment]
I don't think this is the solution. Yes, this solves the problem a little, but it would be better if max fps always worked as it should

**Comment by radfast** [comment]
The issue here is caused by Windows, not by Vintage Story.  We have discussed overriding the Windows system timer but that is controversial, because it might cause unexpected behaviour in other software which relies on the system timer.

For now, the recommendation, on a Windows system with this issue (not all have this issue), is to set the desired MaxFPS to 65.  Or use VSync.

**Comment by LekKit** [comment]
> The issue here is caused by Windows, not by Vintage Story. We have discussed overriding the Windows system timer but that is controversial, because it might cause unexpected behaviour in other software which relies on the system timer.

FYI: Since Windows 10 1803+ you can use `CreateWaitableTimerExW()` WinAPI function with `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION` flag to obtain a high resolution timer handle, then you can set a timeout for it in 100-ns units via `SetWaitableTimer()` and wait on it using `WaitForSingleObject()` to implement proper high-resolution sleep

I primarily code in other languages, but I hope the following simplified example can be adapted. I am using it in my C project which needs precise delay timings and so far it worked really well without an issue.

```c

// Accepts nanosecond delay, will fallback to coarse implementation on older OS versions
void high_resolution_sleep(uint64_t ns)
{
    // CreateWaitableTimerExW() API exists since Vista, high-resolution flags since Win10 1803+
    uint32_t flags = CREATE_WAITABLE_TIMER_MANUAL_RESET | CREATE_WAITABLE_TIMER_HIGH_RESOLUTION;
    HANDLE timer = CreateWaitableTimerExW(NULL, NULL, flags, TIMER_ALL_ACCESS);
    if (!timer) {
        // This OS doesn't support CREATE_WAITABLE_TIMER_HIGH_RESOLUTION
        timer = CreateWaitableTimerExW(NULL, NULL, CREATE_WAITABLE_TIMER_MANUAL_RESET, TIMER_ALL_ACCESS);

        // It might be a good idea to put scheduler into low-latency mode via NtSetTimerResolution() once
        // Yeah, it will waste some power - but those systems are old anyways and it's a game...
        call_once(scheduler_low_latency_mode);
    }
    if (timer) {
        // We may use precise delays in 100ns units
        LARGE_INTEGER delay = {
            .QuadPart = -(ns / 100),
        };
        SetWaitableTimer(timer, &delay, 0, NULL, NULL, false);
        WaitForSingleObject(timer, INFINITE);
        CloseHandle(timer);
    } else {
        // CreateWaitableTimerExW() failed miserably
        Sleep(ns / 1000000);
    }
}

```

Note that it might be a good idea to maintain a thread-local waitable timer, and create/close it once per thread to save the overhead of `CreateWaitableTimerExW()`/`CloseHandle()`, which in my experience is not even measurable though. This is beyond this example.

As for older systems, I'd advise to actually put the scheduler into low-latency mode (As can be seen at line `call_once(scheduler_low_latency_mode)`). It can be done like this:

The scheduler low-latency mode only persists until the process exits, so this is not a huge concern on long-term power usage (Don't play games if you wanna save battery - simple as that)

```c
// Call this once on systems which DON'T support CREATE_WAITABLE_TIMER_HIGH_RESOLUTION
void scheduler_low_latency_mode()
{
    int32_t (*__stdcall nt_set_timer_resolution)(ULONG, BOOLEAN, PULONG) = GetProcAddress(GetModuleHandleA("ntdll.dll"), "NtSetTimerResolution");
    if (nt_set_timer_resolution) {
        ULONG cur = 0;
        nt_set_timer_resolution(5000, TRUE, &cur);
    }
}
```

**Comment by Craluminum2413** [comment]
@radfast Would this be useful to fix Max FPS setting?
https://github.com/anegostudios/VintageStory-Issues/issues/1133#issuecomment-3125656531
