### ISSUE TITLE
Unclear crafting output with recipes that match the same input items (but different amounts)

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1146]
**Game Version:** X.Y.Z  
**Platform:** Windows 
**Modded:** No

### Description
If there are two recipies with the same ingredients in the same positions but different amounts the one with the smaller amount is ALWAYS applied.
example: leather bracers and heavy leather gloves

### How to reproduce
1. try to craft heavy leather gloves

**Comment by Craluminum2413** [comment]
Yes
![image](https://user-images.githubusercontent.com/69315569/125276084-79603300-e318-11eb-9682-afd0a845d76a.png)

**Comment by Craluminum2413** [comment]
The same for high leather boots
![image](https://user-images.githubusercontent.com/69315569/125276351-cba15400-e318-11eb-9f67-1dacf3185860.png)

Also a question: Should they always be crafted with 0% condition? Or do they can be crafted with higher condition? Because sometimes I get clothes with better condition, just from crafting.

**Comment by copygirl** [comment]
Is it clear whether this is a bug? If two recipes match the same input, then the outcome is unclear. Which **did** you mean to craft?

Sure, you could make it so there is a priority for the recipe output to pick the recipe with more input items, but ... I'm not sure. This seems confusing. What if someone meant to craft the high leather boots but did not put enough leather in all slots, accidentally crafting the wrong thing because they were not paying full attention.

**Comment by Craluminum2413** [comment]
What if there was some sort of switch to the right of the crafting grid?

**Comment by copygirl** [comment]
Yes that is what some Minecraft mods allow you to do, to fix an issue where multiple mods add the same recipe. However, this is a recipe conflict that's present in the Vanilla game and could or perhaps should be resolved by adjusting the recipes themselves.

(I also think the right solution to recipe conflicts in Minecraft is modpack creators adjusting recipes.)

**Comment by sirStroam** [comment]
The ultimate solution is to add in tailoring mechanics and remove the grid recipes for clothing however that's not happening this release. I think the short-term solution is either adding a new asset like heavy leather or changing the conflicting recipes.

**Comment by tyronx** [comment]
thanks for the report, for now we'll just use different recipes in rc.4
