### ISSUE TITLE
Creatures manually spawned in a wall can walk through it

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1165]
**Game Version:** 1.15.0-rc.3
**Platform:** Windows
**Modded:** No

### How to reproduce
1. Make a wall, like 10x10
2. Spawn any creature (using their item from CreativeInventory/Creatures) on it
3. It spawned in a wall and can walk through it

### Expected behavior
You spawn them like in minecraft

### Videos

https://user-images.githubusercontent.com/69315569/125624634-bb540153-dc40-4525-aa8a-62aac21a066d.mp4

**Comment by copygirl** [comment]
This is because the creatures are spawned in the middle of the neighboring block, but wolves are wider than one block, so they spawn "partially inside" said block, which allows the entity to move through.

We could:
- Fix the spawning behavior so that larger entities are instead spawned further away from the wall. This doesn't completely eliminate the problem on its own, as the entity could still get stuck in other, surrounding walls. So either take those into account too, or prevent the spawning and note that there's not enough space.
- Work around the issue by pushing entities out of blocks, if they happen to get stuck inside them somehow. Again this isn't a complete solution because what happens if the entity is surrounded by blocks on both sides?
- ~~Damage entities stuck in block so they eventually die.~~ I don't like this.

Either, this is a scenario that should not occur in survival. Entities should not get stuck in blocks, and if they do somehow, we should fix the cause of that, first. If creative players are aware of this behavior, the "bug" can be avoided.
