### ISSUE TITLE
Bell pepper seeds unplantable in 1.15.1

### ISSUE THREAD

**Issue by Jamie-Louise** [anegostudios/VintageStory-Issues#1178]
**Game Version:** 1.15.1
**Platform:** Windows
**Modded:** No

### Description
I cannot plant bell pepper seeds.

### How to reproduce
1. Obtain bell pepper seeds.
2. Right-click to plant on farmland.
3. Nothing happens.

**Comment by Craluminum2413** [comment]
Absolutely not a bug. [1.15.0 (Stable)](https://www.vintagestory.at/forums/topic/5104-the-homesteading-update-v1150/?tab=comments#comment-23519)
> One more new crop, Bell pepper, is generated in the world and will drop seeds, but the seeds are not yet plantable (this will come in a future update)

**Comment by radfast** [comment]
I guess we should have given an error message.  At this point it's more likely we will finish programming this and re-enable these seeds in a future 1.15.2.

The reason for keeping the crops and the seeds in 1.15.0 and .1 even though not plantable, is because a lot of players will be either making new worlds, or visiting the warmer regions of current worlds, looking for some of the new crops and woods.  At least this way the player can find Bell pepper plants and seeds in the wild.

**Comment by Jamie-Louise** [comment]
Ok. I didn't see the info on the stable release page. I grew some in the unstable release and was confused when it didn't work after updating.
