### ISSUE TITLE
Water edge graphical bug

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#125]
There's an inexplicable wall in my water.
![2018-05-26_23-52-08](https://user-images.githubusercontent.com/10406037/40582307-d0718a30-613f-11e8-9523-dd691276163c.png)
![2018-05-26_23-50-20](https://user-images.githubusercontent.com/10406037/40582304-c5a4bc08-613f-11e8-81df-4a7079eee2c9.png)
Reloading fixes the issue, but it was still strange. It might be related to playing for an extended period of time

**Comment by sirStroam** [comment]
on worldgen issues please include the seed and coordinates.

**Comment by Balduranne** [comment]
@sirStroam How do I get the world seed?

**Comment by sirStroam** [comment]
`/seed`
http://wiki.vintagestory.at/index.php?title=List_of_Chat_Commands

**Comment by tyronx** [comment]
Is this bug still around?

**Comment by Balduranne** [comment]
I'm afraid I don't know. Tatsu says it's a cache problem, and I haven't played the game since

**Comment by tyronx** [comment]
assuming to be fixed as it hasn't been reported in over a year

**Comment by Zaldaryon** [comment]
**Game Version:** 1.12.9-rc1
**Platform:** Windows 10
**Modded:** No

### Description
I've found a way to reproduce the water lake leveling worldgen bug.

### How to reproduce
1. Find a lake that *is not below the sea level (example: water that starts on level 110 or up)* and that occupies more than 1 chunk;
2.  Use /wgen regen 0 on one of the chunks;
3. Look the discrepancy;
4. Use /wgen regen with a number that ocuppies all the lake. (normally 1 or 2 for small lakes);
5. The leveling is fixed;

### Expected behavior
It might have to do with lake chunks generating at different times. If possible, this part of worldgen might be checked, or at least you might guarantee that all the lake chunks load at the same time.

### Screenshots
![2020-03-17_12-52-38](https://user-images.githubusercontent.com/50756284/76875669-a3523400-684f-11ea-82e3-e64a442ef4b4.png)
![2020-03-17_12-52-51](https://user-images.githubusercontent.com/50756284/76875672-a51bf780-684f-11ea-8611-a1a043feac3e.png)

**Comment by copygirl** [comment]
@Zaldaryon This bug is about a graphical glitch. Yours is a (known) worldgen bug. Thanks for the effort trying to find an existing issue, but in this case, may I ask you to open a new one?

**Comment by Zaldaryon** [comment]
Sure! Just did it.
