### ISSUE TITLE
add operation in certain cases can replace

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1418]
**Game Version:** 1.15.9 
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
`add` operation can act as `replace`, if the same attribute already exists. For example, it is okay if item doesn't have `behaviors`, but if it has (added by some mod, new vanilla update etc.) then it replaces the whole attribute

### How to reproduce
1. Make sure that item/block/entity has certain attribute e.g. `behaviors`, fill it with any information
2. Make a patch that "creates" that attribute again, e.g.
```json
  {
    "op": "add",
    "path": "/behaviors",
    "value": [{ "name": "GroundStorable", "properties": {"layout": "Quadrants"}}],
    "file": "itemtypes/food/pickledlegume.json"
  },
```
3. It replaces the whole attribute

### Expected behavior
Gives an error that such attribute already exists

**Comment by copygirl** [comment]
When you have a JSON file that looks like this
```js
{
  "behaviors": [
    { "name": "GroundStorable", "properties": { ... } }
  ]
}
```
and then you apply your patch, it will look like this:
```js
{
  "behaviors": [
    { "name": "GroundStorable", "properties": { ... } },
    { "name": "GroundStorable", "properties": { "layout": "Quadrants" } }
  ]
}
```
There is no error the JSON patcher can detect this as an error, because it isn't. `add` simply adds new entries. Nothing is overwritten. The only thing that could happen here is for the code that registers behaviors from JSON to error due to multiple behaviors of the same name being added.

I personally would prefer it if the layout was `"behaviors": { "GroundStorable": { <properties in here> } }`, but that's a breaking change. This way patching would not have to "guess" the index of behaviors it's trying to modify for example.

**Comment by Craluminum2413** [comment]
Then I guess it can be closed
