### ISSUE TITLE
Barrel cactus texture glitch

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1606]
**Game Version:** 1.16.1-rc.2
**Platform:** Windows 
**Modded:** No  
**SP/MP:** Singleplayer

### How to reproduce
1. Place a barrel cactus
2. Fly/run around it by different angles while looking at it
3. By some angles, you can see texture glitches

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/149932603-299c47a5-43dd-469d-8cc7-2f081d631e11.png)
![image](https://user-images.githubusercontent.com/69315569/149933085-4496d2d1-5c03-4963-afab-709b892cc477.png)
![image](https://user-images.githubusercontent.com/69315569/149933221-3a246144-8b9e-4871-82ba-1e462513a9d4.png)

**Comment by RedramVS** [comment]
If the intended target here is how the spines appear grey from steep angles, I think that was fixed since this was reported.  I could not reproduce it.  If someone else still gets it, feel free to reopen. 
But even if still there, I don't think it's a glitch with barrel cactus, it would be more of a shader or other general graphical glitch, when viewing mono-planes at steep angles.  I did do some very slight size and angle changes, to try to eliminate z fighting between adjacent patches, due to random rotation and placement.
