### ISSUE TITLE
Weird black outline along 'rug' blocks

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#163]
![2018-07-31_19-45-35](https://user-images.githubusercontent.com/10406037/43493194-b1e5ba7a-94fa-11e8-8489-4ef0d14fe594.png)
From the moment I added my pelt blocks, they've had this black outline when I've been some distance away from them. They look normal when I'm close or standing on them, but as soon as I walk away, it's back to the outlines. At first I thought it was something with how I did the wolf pelts, but it seems like a bigger issue.

**Comment by tyronx** [comment]
Yea, this is a silly bug. It caused by the transparent pixels on your rug textures being black. You have to make them the color of the rug, then the effect goes away.

For the vanilla assets I wrote myself a script that determines the average color of all opaque pixels and draws that RGB value into all the transparent pixels.

Example a parsnip crop stage:
![e8](https://user-images.githubusercontent.com/762006/43507986-4b75fa84-9577-11e8-9db5-9d3915845508.png)
And with the alpha channel removed:
![e8nt](https://user-images.githubusercontent.com/762006/43508001-5348b65c-9577-11e8-9d9f-336aca655e93.png)
