### ISSUE TITLE
WIKI is down. Timeout.

### ISSUE THREAD

**Issue by hoblin** [anegostudios/VintageStory-Issues#1677]
Everything is in the title =)

**Comment by copygirl** [comment]
Website related issues like availability are probably not a good fit for the issue tracker. Partially because this is the kind of issue that typically doesn't need to be tracked. Just inform the devs on Discord - where they can see and respond much more quickly. (Issues are only checked every once and then.)

Either way, the wiki is accessible for me at the moment so it may have either been a temporary issue that went away on its own or already got resolved.
