### ISSUE TITLE
Pressing a GUI key such as M while in the creative search opens it

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1729]
**Game Version:** 1.16.3
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** **No** / Yes (which?)  
**SP/MP:** **Singleplayer** / **Multiplayer** (which?)  

### Description
Explain the issue you're running into.

Pressing a GUI key such as M while in the creative search opens it.

### How to reproduce
1. Open creative menu
2. Start searching
3. Type something that happens to have M or another GUI key in the name
4. Map opens while searching

### Expected behavior
If not obvious, what did you expect to happen?

Map / related GUI does not open.

**Comment by Craluminum2413** [comment]
Do you have VSHUD installed? If yes, then it can be a problem

**Comment by l1ving** [comment]
Nope.

**Comment by ApacheTech** [comment]
When typing in the in-game chat window, whenever you press "g", your character sits down/stands up. Bug has been present since at least game version 1.12.

To reproduce:

1. Keep "g" as standard sit/stand keybind.
2. Load into world. Make sure your character is standing up.
3. Type into game chat: "I am now sitting.".
4. Your character will now be sitting down.
5. Type into game chat: "I am now standing.".
6. Your character will now be standing up.

Expected behaviour:

Keybinds like this should be disabled, while typing in chat.
