### ISSUE TITLE
Ebony crates are listed as ingredients for aged crates

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1799]
**Game Version:** 1.16.4
**Platform:** Windows / Mac / **Linux** (which?)   
**Modded:** No / **Yes** (which?)  
**SP/MP:** Singleplayer / **Multiplayer** (which?)  

![image](https://user-images.githubusercontent.com/17222512/158001882-85f3cbca-166d-4ea0-ba4b-c87b6c35892e.png)

**Comment by Craluminum2413** [comment]
All crates act that way

**Comment by CookieBoy21** [comment]
Issue can be closed because it's look like they fixed it and all crates act correct in handbook.
Here is example photo:
<img width="1280" alt="Vintagestory Screenshot 2024 05 04 - 17 17 58 77" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/acc5be73-1dcc-4582-8562-254a29442c79">
