### ISSUE TITLE
Torch (placed) dont goes out in water

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1921]
**Game Version:** 1.17.0-pre.1
**Platform:** Windows
**Modded:** Yes 
**SP/MP:** Singleplayer 

### Description
torch underwater

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
![image](https://user-images.githubusercontent.com/40342734/173607429-e436daf1-a6a4-4955-b312-e276eba14d7d.png)

**Comment by wasakoki** [comment]
lit campfires and pretty much any block that involves a heat mechanic don't extinguish too. you can also place flowers underwater and tree seeds, which do grow into full trees. crops cant be placed directly into water but are otherwise also completely unaffected if they are submerged in water after they were placed. (i.e. a flooded farm from a poorly placed water bucket)

**Comment by Craluminum2413** [comment]
Fixed in v1.18.2-rc.1
