### ISSUE TITLE
Crock get empty when content is rotten

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2012]
**Game Version:** 1.17.0-pre3
**Platform:** kubuntu
**Modded:** No 
**SP/MP:** Singleplayer survival or creative

### Description
When the content of a crock is rotten, the crock gets empty when taken in inventory.

### How to reproduce
1. Fill a crock with some meals
2. Wait until its content is rotten
3. Take it into your inventory. The crock is empty.

### Expected behavior
The crock should contain rot that can be thrown to the compost barrel.

**Comment by tyronx** [comment]
Heya, I think what you are observing here is a feature, not a bug. 

There is a conversation factor from food item -> rot. Sometimes it does not convert to 1 full rot - in those cases the game decide randomly to place one rot or have it be empty. This should happen especially if you only had few servings and or meals with few ingredients.

If you think otherwise, please reopen the ticket.
