### ISSUE TITLE
Pressing Q (drop item) in dialog should drop item that's hovered over

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#234]
Currently it drops the currently held item.

**Comment by copygirl** [comment]
Apparently it's already in `1.8`.

**Comment by Heptagon-ru** [comment]
I now remember I was slightly annoyed by a similar behavior, when you right-click on an item and it appears not in the currently selected hotbar slot, but in the first free one. E.g. when taking something from a tool rack, or a bowl, ...
I guess I should confirm the "issue" next time I play and create a ticket. Hopefully won't forget :)

**Comment by copygirl** [comment]
I tried to look for an issue, but I guess it's not there yet. I have been suggesting this before as well. Holding an item on the mouse cursor should make it your currently held item as well. I think that could unify a lot of the in-world interactions with the cursor.

Would be awesome to be able to right click food in your inventory to use it, too. And to use blocks directly without having to place them in your hotbar.

**Comment by copygirl** [comment]
@Heptagon-ru By the way I made some code to rework floaty GUIs. I got rid of the "Hold `Ctrl` to move camera while mouse is free" feature and inverted it. It will now be "Hold `Alt` to unlock the mouse while it's grabbed". It comes with a new setting that makes it so chests and other floaty GUI in-world blocks don't release the mouse anymore. So you just move your crosshair over slots to interact with them, or press `Alt`.

The other stuff I'm hoping to implement, too.

**Comment by Heptagon-ru** [comment]
It will be vanilla functionality? Sounds nice, need to use in practice to see how comfortable it will be.
First I thought that always pressing an extra key will be cumbersome, but maybe using crosshair for managing inventory will also be comfortable in most cases. So Alt key will not be used too much. And even when used will still be comfortable. Will see.

Do you plan to somehow improve the "close chest" implementation in floaty gui mode?
It was discussed long ago, iirc that the distance at which chest closes is too big and e.g. I never close them with walking back, and have to use Esc key, which is uncomfortable to press, too far from WASD. Iirc one of ideas was to close them maybe with double pressing S or maybe just make the "closing" distance much shorter. Well, not the distance, but probably the difference between the initial "opening" distance and the "closing" one.

**Comment by copygirl** [comment]
Maybe [this](https://twitter.com/koppeh/status/1068146549002305537) gives you a better idea of what it would look / work like.

**Comment by Heptagon-ru** [comment]
Thanks. This is what I approximately imagined about the implementation. Need to see in practice after 1000 various interactions with inventories etc. :)
Btw, I have just realized that my greatest fear about the new interface - that it might be less accurate and precise when working with small items in grid - is in vain, because the mouse movements are absolutely the same in both interfaces. Just the surrounding picture moves in the new one, while in the old one it was still. And moving is better, because now you have better access to the whole 3D sphere around you without a need to press a special button to move the camera. I.e. all the inventory guis around you are now seamless.
Altho I'm not sure now how it will work with the inventory gui, which is fixed on the screen.
Often when you interact with storages, you need your inventory open and the crafting grid.
But their guis are fixed and they will I guess force mouse cursor to appear, which will break the seamless access to all storage guis around you ...
Will see ... :)
