### ISSUE TITLE
On the topic of kapok logs turning into 3x firewood each

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#235]
.. instead of the usual 4x firewood for every other tree type.

> **Saraty:** it's because they grow much bigger then other trees when planted

It stills costs the same amount of durability to cut down each log. Thus, the durability cost per each piece of firewood is larger. While this might be intended, what about just making it so bigger trees simply take longer to grow? It would simplify things for users if 1 log => 4 firewood regardless of the type.

**Comment by Heptagon-ru** [comment]
+1
Considering that soon after you start tree farming you have enough saplings and have no problem to plant 2-4 oaks instead of one kapok to get the same amount of logs (and pay with the same durability price for harvesting), it feels more expected to get the same 4 firewood from kapok log.
Moreover, since kapok log is inferior vs. oak log as fuel, I would actually prefer to get more than 4 firewood from kapok, otherwise I would not even consider farming it for any kind of fuel.
Similarly e.g. it would be nice to get significantly more firewood from acacia because it is a very uncomfortable tree to farm.
Anyway, I feel that firewood is not a game mechanics worth enhancing, adding perks, etc.
So making players to pay too much attention to such perks feels undesirable, better unify it to 4.

**Comment by tyronx** [comment]
@copygirl that still will leave you with extra firewood when chopping down native jungles. 

If we give 4x firewood yield to kapok, I would like to counter it with something. e.g. implement that you can grow kapok only in warm and wet climates.

**Comment by copygirl** [comment]
What about just making trees not native to their natural biome grow slower? On top of being affected by their size. Maybe they could require farmland? Fertilizer?

> If we give 4x firewood yield to kapok, I would like to counter it with something. e.g. implement that you can grow kapok only in warm and wet climates.

That would still not address your own point though:

> that still will leave you with extra firewood when chopping down native jungles.

**Comment by Heptagon-ru** [comment]
Added a personal suggestion related to/insppired by this ticket:
https://www.vintagestory.at/forums/topic/701-ability-to-grow-big-trees-eg-in-native-biome/

**Comment by Craluminum2413** [comment]
In 1.15, purpleheart and ebony use 3x firewood too

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
