### ISSUE TITLE
Macro Bindings lost in update to .net 7

### ISSUE THREAD

**Issue by OpPointBaker** [anegostudios/VintageStory-Issues#2368]
### Game Version

v1.17.11-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Key bindings for macros no longer functioning. I had to assign again the hot keys for each macro and edit the macro itself slightly [I added a space at the end of the macro command] in order for the hotkey to update.

### How to reproduce

Make macros in 1.17.10 and then update to 1.17.11-rc.1 

### Logs

```Log```

**Comment by Th3Dilli** [comment]
thank you for the report, this will be fixed partially in the next release

since the keymapping in opentk3 and opentk4 do not match there are some key combinations that cant be migrated but all general keys should be mapped automatically to opentk4 now

Here are the relevant enums for reference
OpenTK3:
https://github.com/opentk/opentk/blob/3.x/src/OpenTK/Input/Key.cs
OpenTK4
https://github.com/opentk/opentk/blob/master/src/OpenTK.Windowing.GraphicsLibraryFramework/Enums/Keys.cs
