### ISSUE TITLE
Farmed cabbage not growing in unloaded chunks

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#241]
1.8.5, chrometech.

For some time I have noticed that cabbage grows much less than I expect it.
I.e. when I return to server when some people are playing on it, and I know they play quite often and for long enough time, I see that my cabbage did not get any growth stages.
Also when I was running exploring, when returned, I also see cabbage is the same stage as when I left.
According to devs, it grows following the calendar and should grow in unloaded chunks when people are on the server.

I made a test:
1. Created fresh farmland from high ferrtility soil
2. Planted cabbage on it.
3. Run away about 500 blocks (from my base 350 -550 to Spawn)
4. Waited there for about 50 mins, slept twice or three times in medium bed.
5. Returned to base and waited 5 mins

All 34 cabbage was in stage 1.

I believe it might be broken, and it does not grow when chunks are unloaded, please test and fix that.

**Comment by copygirl** [comment]
Could you confirm that after staying a while in the previously unloaded chunks, the cabbages don't update eventually and adjust according to the "calendar"? And it's just those and not other crops?

**Comment by Heptagon-ru** [comment]
I waited 5 minutes to see if some of cabbages from the 34 planted would suddenly grow according to calendar.
It did not happen.
If I stay longer, they might start growing just because I stay in the area for long enough time.

About other crops - I don't know. The experiment takes too much time, so I was able only to do this one.
I don't plan to spend more time on experimenting.

**Comment by tyronx** [comment]
Oh I think I know what its caused by. The Farmland checks if its watered every 15 seconds. Crop growth is tested for every 2 seconds. Farmland is considered moist when it was watered by a watering can or by nearby water within the last 24 ingame hours.

So if an ingame chunk is getting loaded after 24 ingame hours the water test basically always fails (= farmland is considered dry) and the crops don't fast forward their growth. 

This is now account for and thus unloaded chunk crop growth should work as intended in v1.9. Thanks for testing and reporting.
