### ISSUE TITLE
Screenshots not saved in Flatpak version

### ISSUE THREAD

**Issue by JulianGro** [anegostudios/VintageStory-Issues#2567]
### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When creating a screenshot using F12, it will tell you the file name, but that file does not exist anywhere.

### Logs

```Log```

[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/11200444/Logs.zip)

**Comment by DArkHekRoMaNT** [comment]
Flatpak are not officially supported by team. Maybe @jascrain (maintainer of [flatpak repo](https://github.com/flathub/at.vintagestory.VintageStory)) can help you

**Comment by DArkHekRoMaNT** [comment]
In the regular version, it is saved in $HOME/Pictures, afaik

**Comment by mard** [comment]
@JulianGro, thank you for reporting this problem.

It has been fixed in latest VS Flatpak update, with the assumption that the game saves screenshots into the `XDG_PICTURES_DIR/Vintagestory` directory. `XDG_PICTURES_DIR` refers to the XDG pictures directory that is configured in the user's desktop environment, so typically screenshots can be found in `~/Pictures/Vintagestory`.

This issue can now be closed. If you encounter more problems specific to the Flatpak distribution of Vintage Story, I would really appreciate it if you report them to the [Vintage Story Flatpak repository](https://github.com/flathub/at.vintagestory.VintageStory/issues) instead.

**Comment by Th3Dilli** [comment]
thank you @jascrain, @mard and @protheory8 for taking care of the flatpak version ❤️ 

further if one uses a custom dir you can use something like [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal)

to add those directories to the allowed ones to access by the VS flatpak
