### ISSUE TITLE
Animals killed by a sling are not killed by a player

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2583]
### Game Version

1.18rc2

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

I killed these rabbits with a sling and some andesite stones. They all say they were killed by another creature.
![image](https://user-images.githubusercontent.com/13642054/231520299-c07bae55-518f-46df-b06f-9c663c1497e0.png)

### Logs

```Log```

**Comment by noelle-lavenza** [comment]
This is because 1.18.0-pre1 changed the damage arguments for thrown stones:
```
                    bool didDamage = entity.ReceiveDamage(new DamageSource() { 
                        Source = EnumDamageSource.Entity, 
                        SourceEntity = this, 
                        CauseEntity = FiredBy, 
                        Type = EnumDamageType.BluntAttack,
                        DamageTier = DamageTier
                    }, Damage);
```
`CauseEntity` is used only for death messages, and if unset the death message defaults to `SourceEntity` anyway. I think there's a good use-case for having these two be separate, so the solution to this issue would be in `Entity.Die()`:
```diff
-                   Entity byEntity = damageSourceForDeath.SourceEntity;
+                   Entity byEntity = damageSourceForDeath.CauseEntity ?? damageSourceForDeath.SourceEntity;
```
EntityProjectile should also then be updated to use `firedBy` as its `CauseEntity` rather than `SourceEntity`. Then, you'd also need to update some other places:
- `SystemTemporalStability.Event_OnEntityDeath` should probably use `damageSource.CauseEntity ?? damageSource.SourceEntity` instead of just `damageSource.SourceEntity`.
- `EntityLocust.ReceiveDamage` should use `damageSource.CauseEntity ?? damageSource.SourceEntity` to account for both melee and thrown boulders
- `AiTaskBaseTargetable.OnEntityHurt` should probably use `damageSource.CauseEntity ?? damageSource.SourceEntity`
- `AiTaskSeekEntity.OnEntityHurt` should probably also use that.
- `EntityBehaviorEmotionStates.OnEntityReceiveDamage` should probably replace `long sourceEntityId = damageSource.SourceEntity?.EntityId ?? 0;` with something like `long byEntityId = damageSource.CauseEntity?.EntityId ?? damageSource.SourceEntity?.EntityId ?? 0;`, but chained null coalescing operators like that can get kind of difficult to read and follow. Also, `damageSource.SourceEntity != null` should be changed to account for `CauseEntity` as well.

These should *not* be changed to use `CauseEntity`:
- `ModSystemWearableStats.applyShieldProtection` needs to know the angle to the source of the damage rather than to whoever fired it, otherwise you could do some really weird things to get around shields if you're fast enough (or if the projectile is slow enough)
- `Entity.ReceiveDamage` uses `damageSource.GetSourcePosition()` to determine knockback direction, which should be from the actual damage source rather than the entity controlling it.

I'm unsure about `EntityPlayer.OnHurt`, mostly for balance reasons relating to damage reduction.

**Comment by Monolithys** [comment]
and same, when killed by rock from empty hands

**Comment by Th3Dilli** [comment]
thank you for the report
and thanks noelle-lavenza for the details 😊 

this will be fixed with the next release
I did took a look at all references to DamageSource and updated it's usage of SourceEntity and CauseEntity where necessary by using a new method on DamageSource `GetCauseEnity() => return CauseEntity ?? SourceEntity`
