### ISSUE TITLE
1.18.0-rc8 -- Text bugs and missing translations

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2605]
### Game Version

v1.18.0-rc8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I made sure that the French Crowdin file was 100% complete and downloaded it from there before checking for those bugs.

### Screenshots

![Bug 01](https://user-images.githubusercontent.com/26251843/232565800-a63d1d7c-9ff6-4260-8aa6-43a1613b7791.png)

![Bug 02](https://user-images.githubusercontent.com/26251843/232565849-b1380468-55ee-44b8-9fa6-505155cdf8bb.png)

![Not translated 01](https://user-images.githubusercontent.com/26251843/232565895-e60ea79c-54d9-4a3b-b700-7d35674e774b.png)

![Not translated 02](https://user-images.githubusercontent.com/26251843/232565907-52489b0a-9568-432c-a683-4dedb459c4a3.png)

![Not translated 03](https://user-images.githubusercontent.com/26251843/232565923-670e08dd-f575-4b99-8d70-80658cc151a0.png)

![Not translated 04](https://user-images.githubusercontent.com/26251843/232565940-d5729bee-be60-49e7-a61b-520af5aee586.png)

![Not translated 05](https://user-images.githubusercontent.com/26251843/232565955-f727a83c-e73e-4afa-89ba-9bc9e9ad5206.png)

![Not translated 06](https://user-images.githubusercontent.com/26251843/232565967-dc8d4d3f-fc86-40cc-a555-6149e4f8e706.png)

![Not translated 07](https://user-images.githubusercontent.com/26251843/232565992-3f99f92e-43f7-43ff-ace9-81c81b650805.png)

![Not translated 08](https://user-images.githubusercontent.com/26251843/233075821-1575e0b8-299c-46e9-9691-1ca8f4e8e3c2.png)

**Comment by daretmavi** [comment]
Tutorial problem is present even with English language.
![obrázok](https://user-images.githubusercontent.com/47914240/232849314-ca9e1f10-0c96-450b-b2c6-e086b1ec6cc6.png)

**Comment by Craluminum2413** [comment]
Is it fixed for you?

**Comment by radfast** [comment]
@Xandoria thank you always for raising the missing / non-working Localizations with precision.  I apologise it took us so long to get this, frankly I forgot but then rediscovered this issue today while searching for something unrelated.

I believe that all are now fixed in next upcoming 1.20.0-rc.5.

In more detail:

I think that several have previously been fixed over versions since 1.18.0-rc.8: the solid doors, the tutorial, the handbook 'Search...' text and 'Pause game' text, the required traits (e.g. bowyer), the metal/wood type of shields, the name of bucket contents, and the damage source when killed by a thrown stone, all now look OK.  (If I am wrong about one of these, please state it here, and we can investigate some more.)

I've now fixed:

- the Damage log recording for HP gained through "heal" or lost through other damage types
- the Condenser
- the Fruit Press
- one more place where "Search..." was seen even in French (the Browse public servers list when searching for a multiplayer game)
