### ISSUE TITLE
Cellar food preservation broken

### ISSUE THREAD

**Issue by oxxyjoe** [anegostudios/VintageStory-Issues#2755]
### Game Version

1.18.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Food stored in cellars spoils much faster than normal since updating to 1.18.5. 

Containers, crocks, bowls etc report a much longer time they will last than when you pick them up. 

### How to reproduce

Make a cellar of any size and place food in it. Tooltips show 0.28 rate of decay, but when you pick up the food it will have decayed at non-cellar rates, sometimes "spoiling immediately."

### Logs

```Log```

**Comment by Craluminum2413** [comment]
What happens win th cellar that have no doors?

**Comment by oxxyjoe** [comment]
> What happens in cellar that have no doors?

My cellar had no door, so, this.

**Comment by DArkHekRoMaNT** [comment]
> Containers, crocks, bowls etc report a much longer time they will last than when you pick them up.

Looks like normal behavior. The cellar bonus does not work for the player

**Comment by radfast** [comment]
I did make changes to container code in 1.18.5, may have broken something

**Comment by oxxyjoe** [comment]
> > Containers, crocks, bowls etc report a much longer time they will last than when you pick them up.
> 
> Looks like normal behavior. The cellar bonus does not work for the player

Normal behavior is that it applies the cellar bonus to items you put in the cellar, rather than carry on you. 
This is true I think. But this is not normal, rather, this is bugged, because, the "time left until it spoils" will say, for example, '5 days,' while sitting on the cellar floor, but when I picked it up, it will instantly change to "30% spoiled." 
That is evidence that it is reporting to the player an incorrect "time left" value, and, that is indicating that the cellar bonus is not actually applying to the item.

**Comment by Craluminum2413** [comment]
That means that cellar bonus doesn't apply to items stored on the ground

**Comment by Echoweaver** [comment]
There's definitely something going on here. I expect when I pick up an item from the cellar that its spoilage time will advance when I pick it up. However, it should go back down when I put it back. That doesn't happen. I picked up a crock with 14 days left. It advanced to 7 days in my inventory. When I put it on the floor, it stayed at 7 days.

I've also picked up items that are listed as having several days of freshness left, and what is added to my inventory is rot.

I'm on a multiplayer server if that's relevant.

**Comment by radfast** [comment]
Is anyone having this issue for fresh food not in containers (berries, meat etc)?    Or only for crocks and bowls?

If it's crocks and bowls, does the issue happen if you don't place them on the ground, for example if you transfer directly from a storage vessel in the cellar to the player inventory?

**Comment by Prinzip** [comment]
people complain that pots with quality very quickly lose their durability. As a result, many pots have rotted in players, although on the rack the durability was still given. If you take the pot from the rack, all of a sudden it goes bad. VS 1.18.5. Here is an example:


![1](https://github.com/anegostudios/VintageStory-Issues/assets/19502273/bd825d1c-cccd-459d-937c-229e2f2e02f0)
![2](https://github.com/anegostudios/VintageStory-Issues/assets/19502273/7075b406-becd-4c79-b2ab-d171f2588882)
![3](https://github.com/anegostudios/VintageStory-Issues/assets/19502273/e6edf833-a03f-4929-b5fe-50618299d364)

**Comment by radfast** [comment]
Thank you for all the reports.

Unfortunately, this is a new bug introduced in 1.18.5.

It applies only to crocks, bowls, cooking pots - basically any placeable/holdable container which holds food

The bug only happens if the container is in a storage place which holds **_no raw or uncontained food_**

Example:

-  a Cooking pot on the ground has the bug  (no raw food can be stored on the ground)
-  a Crock on a shelf has the bug unless there is cheese also on the shelf  (no raw food can be stored on a shelf, but cheese is uncontained food and can be stored on a shelf)
- a Crock inside a Chest or Storage Vessel, and the same Chest or Storage Vessel also holds - for example - some grain or vegetables:  no bug

Therefore, until this is fixed, my advice to players is:
*  freshly cooked food  (cooking pot / crock / bowl):  store it in a Chest or Storage Vessel which also holds at least 1 item of grain of vegetables
*  existing food  (especially your long-term storage of sealed crocks, jams etc) - **leave it where it is untouched until this bug is fixed**   If you move a food container from a position which has the bug in 1.18.5, it will rapidly spoil
*  if you have the option, for crocks on shelves, do **_not_** remove the crock from the shelf, but if you have this possibility you could try adding some uncontained food item to the same shelf (cheese), that will protect your crock from the bug.

------

We will look to get a fix for this bug out ASAP, I apologise that each recent "stable" version has had a serious bug.

**Comment by oxxyjoe** [comment]
I started a new game in version 1.8.4, and, have just noticed that the issue is occurring to (at least) unsealed crocks in my single player world.

I had an unsealed crock of red meat stew that showed 9 days remaining, on a shelf in the cellar, and upon placing it on a regular stone block, it changed to only 5 hours. And upon replacing it to the shelf, it stayed at 5 hours.

I then picked up a sealed crock that had 1.6 years remaining, 
placed it on the ground, then picked it up, and replaced it upon the shelf,
and it remained at 1.6 years remaining.

Thank you for addressing this and I'm glad to have noticed it.

**Comment by Dracoso18** [comment]
I just had this issue as well. It appears that when you pick up food, it readjusts to time passed since it was first made. I picked up a crock that read 10.1 hours left on a shelf. It immediately went to 100% spoiled. Several crocks at 15-18 days remaining jumped down to between 20 hours and 3.1 days. my friend and I had to stop playing because i was watching our food rapidly go bad across the board. 

Some of the food i made recently which were at 23 days would drop to 21 days if I picked them up. Because of this, i think the food is: 1. when picked up, it jumps to as if it had been at 100% spoil rate since it was first made and calculates the remaining time left, updating the current spoilage rate to that time 2. when placed back down, it shows the updated time and then acts as if the preservation rate is correct in the cellar. 3. if picked up again, it recalculates and adjusts again to the 100% rate update.

**Comment by Guimoute** [comment]
Hello,

There seems to be more at play than expiration date issues. Like everyone else I picked up crocks and their content rotted instantly, but I also got a different behavior where the content disappears altogether instead of rotting. Please see below:



https://github.com/anegostudios/VintageStory-Issues/assets/51537797/6623e685-bf5e-495c-a4f3-81c51c6c4308

**Comment by tyronx** [comment]
this should be fixed in 1.18.6
