### ISSUE TITLE
The default Texture Atlas is too small for modded game

### ISSUE THREAD

**Issue by ncottrill** [anegostudios/VintageStory-Issues#2848]
### Game Version

v.1.18.6-rc.1 .Net7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Upon first installation and connection to the server, many modded textures were not being properly rendered.

A helpful Discord person suggested I change the size of the Texture Atlas, and this fixed 100% of the rendering of textures that I was having. It appears as if the default size (especially width?) was was too small.

I changed the clientconfig.json so that the texture altas was 8192 x 8192. I've had 0 performance issues and all the renders are perfect now.

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for reporting.  The texture atlas size setting is for precisely this purpose.  We don't set the largest size as default because some older GPUs and integrated graphics cannot handle the largest size.  One of Vintage Story's goals is to allow a reasonable gaming experience even on older, average hardware (e.g. a 5-year old non-gaming laptop).

Having said that:

- we are looking at ways to fit more in to the texture atlas in upcoming 1.19 (more precisely, possible two texture atlases for blocks, one for plants and one for all other blocks)
- there is a documentation issue if you could not find this information easily (i.e. with lots of mods change the textureatlas size setting)

Therefore I will leave this open for now, even though the solution you have described is current intended behaviour
