### ISSUE TITLE
Game crashed while hovering over icon in H menu

### ISSUE THREAD

**Issue by siasur** [anegostudios/VintageStory-Issues#287]
Running on 64 bit Windows with 8 GB RAM 
Version: v1.9.3 (stable)

While I was looking at the recipe for the **Reed Basket** in the Handbook I moved my mouse over the small icon under the **Drops when broken** section. As a result my game crashed.

Here is an image. The icon I mean is circled in red.
![2019-05-11_12-38-00](https://user-images.githubusercontent.com/2236705/57568870-5d397200-73ed-11e9-9f02-92bae691cbb0.png)

[See this gist for the stacktrace](https://gist.github.com/siasur/e255e7ef63504563eee1335baaa3f1e7)

**Comment by RTHauke** [comment]
Happens when looking at the Vine Basket as well.  The Vine Basket shows a Reed Basket icon for the dropped item.  Hovering over it causes a crash that looks very similar.

Version: 1.9.3(release)
OS: Linux
Mono: 5.20.1.19
Hardware: 16GB, i7-3770K, nVidia GTX660(v390.116)

https://paste.ee/p/bCoYP#6cvrU5CcNhPUVJyWHGzxMQTqTQl8x37U

**Comment by tyronx** [comment]
thank you, fixed for next version

**Comment by Shinobicrafter76** [comment]
I was just going to report that I had this issue too but looks like a fix is already implemented.
