### ISSUE TITLE
Propick readings don't match ore generation

### ISSUE THREAD

**Issue by Malvaufjf** [anegostudios/VintageStory-Issues#2927]
### Game Version

v1.18.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When using density mode, prospector pick doesn't even report native copper, despite me being in the middle of a large vein

### How to reproduce

Fly to a native chunk deposit and use density search

### Screenshots

![image_2023-07-17_212601230](https://github.com/anegostudios/VintageStory-Issues/assets/86853432/fae3ae8f-707d-4891-827b-f662bd5b73cd)

### Logs

```Log```

**Comment by Malvaufjf** [comment]
![image_2023-07-17_212857493](https://github.com/anegostudios/VintageStory-Issues/assets/86853432/c366793c-8437-44e4-918e-67ce535ebb6e)

**Comment by Craluminum2413** [comment]
They shouldn't match, it is just a chance after all

**Comment by Malvaufjf** [comment]
Ahhh, sorry, my bad, didn't realize that's how it worked from the handbook. Sorry for wasting time

**Comment by RedramVS** [comment]
Also, in the first screenshot, it looks like you're at elevation 117.  This means you're in a *surface* copper deposit.  Surface copper is a separate deposit type from deep copper.  Because surface copper has to show up everywhere, unlike deep copper.  The propick is specifically programmed to ignore the surface copper deposits in density mode, because you'd literally get results everywhere.
