### ISSUE TITLE
Class changes using .charsel are not saved between deaths and leaving/rejoining

### ISSUE THREAD

**Issue by KoboldCrusader** [anegostudios/VintageStory-Issues#2985]
### Game Version

v1.18.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Hosted singleplayer game. Players attempting to change class using ".charsel" works initially, but changes to class made using this method are reverted after player dies or leaves/rejoins world. Have not yet tested appearance changes or if this bug affects host as well.

Will test further and attempt to post logs when able.

### How to reproduce

1. On hosted singleplayer world, players other than host change class using ".charsel" command.
2. Player dies or leaves game.
3. Changes using ".charsel" are reverted, changing them back to their original class.

**Comment by Th3Dilli** [comment]
thank you for reporting 

there is a different issue underlying you can read it in this discord bug report
https://discord.com/channels/302152934249070593/1128013810683351150


but for .charsel to work you first have to allow it for a user (you can do that with `/player playerName allowcharselonce`) so they are not allowed to change their class in the first place by default and due to a bug it still shows as the change in pre 1.18.7 version

was the other player also using the latest version 1.18.7?

**Comment by KoboldCrusader** [comment]
All players were using 1.18.7, using the "/player [playername] allowcharselonce" command worked as intended, so it was definitely the same bug as pre-1.18.7 as far as I can tell.
