### ISSUE TITLE
Some chunks are occasionally loaded with cave lighting

### ISSUE THREAD

**Issue by Azagwen** [anegostudios/VintageStory-Issues#3253]
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was exploring my world, when I started coming across entire chunks which are completely soaked in darkness, similar to the one that can be seen in caves (see game screenshot)

### How to reproduce

I'm am unsure of how to reproduce this, all I did was explore rather far into the world (blue circle is my spawn, red is where I stand in front of the bugged chunk) (see world map screenshot)

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/30528331/db067e24-1220-471e-b069-c0d2be9c7137)

![image](https://github.com/anegostudios/VintageStory-Issues/assets/30528331/9e7f57f9-0762-406c-8302-45e88f668039)

![image](https://github.com/anegostudios/VintageStory-Issues/assets/30528331/edc5d589-969b-4c18-88ac-5a5543aafe7f)

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13463068/client-main.txt)

**Comment by Azagwen** [comment]
Further notes:
Entering these chunks also cuts the background music, just like entering a cave does

**Comment by ngoomie** [comment]
I had this happen once too in multiplayer 1.17.x, the server on Linux, me on Linux as well (a diff machine), and the other person I was playing with on Windows. I intended to get around to submitting a bug report but never did, I'll have to see where I stowed away the world files when we finished up that world to see if I can give more detailed information

**Comment by SublightTachyon** [comment]
Game Version
v1.18.15

Platform
Linux

Modded
Vanilla

SP/MP
Singleplayer

Description
I also had the same issue today playing the game . I am on garuda linux dragonized (an Arch based distro) went away from my base came back and these chunks very near my base where covered in darkness. 

Screenshots

![screenshot vintage story](https://github.com/anegostudios/VintageStory-Issues/assets/88512527/323428df-bac9-44e4-97d8-79b545cdb125)
![screenshot vintage story](https://github.com/anegostudios/VintageStory-Issues/assets/88512527/ec828c66-4a53-4f9d-9bca-2d3ae2b52f1a)
![Screenshot_Vintage Story_2](https://github.com/anegostudios/VintageStory-Issues/assets/88512527/b4d66531-7b6e-42ed-b7b0-fd0b96ac
![screenshot vintage story](https://github.com/anegostudios/VintageStory-Issues/assets/88512527/fac249b5-d162-4b29-be1d-a2e367d0c8bc)
![Screenshot_Vintage Story_2](https://github.com/anegostudios/VintageStory-Issues/assets/88512527/9382fd0f-0cd8-40fa-8287-f72c3595d76e)
b33a).
I had mods loaded unloaded all my mod. restarted the game they are still there. 
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/13769668/client-audit.txt)

[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/13769670/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/13769671/client-chat.txt)

**Comment by SublightTachyon** [comment]
The music did change when i entered one of those. I have not done much caving so I do not know if it changed to cave music or something else.

**Comment by radfast** [comment]
These chunks are not caves, they are places where for some reason, standard surface world generation did not complete its final step ... which is applying sunlight to the chunk.   (The cave sounds system "thinks" it is a cave because it detects caves in a simple way, by looking for regions with no sunlight.)

The most common causes for these dark chunk issues were fixed from game versions 1.18.0 and 1.18.2 onwards.  But dark chunks still sometimes (rarely) occur even now in 1.20.0 - especially in worlds where the game has in the past crashed a few times for any reason (including pre-releases, unstable mods, etc.).  In some cases, the cause of each dark chunk may be logged to file `server-worldgen.log` - it permanently logs the name of the world and the coordinates when the issue first occurs, and that log can then be looked at weeks or months later.

Players continuing to play old savegames (especially worlds first created prior to 1.18.0) might experience the dark chunks issue more often, because a dark chunk was already saved in the savegame.

If there's a fresh 1.20.0 world with dark chunks still occurring in an unmodded game, please bring it to the dev team's attention by opening a new issue (with a copy of `server-worldgen.log`).

**In all cases** any affected player can fix the problem themselves, by going to the relevant place, standing inside the dark chunk and running command `/debug chunk relight`.
