### ISSUE TITLE
Trait 'mechanicalsDamage' don't work

### ISSUE THREAD

**Issue by BarenAD** [anegostudios/VintageStory-Issues#3520]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The watchmaker has -15% melee damage, but +25% damage to mechanisms. But this parameter does not work.
I chose the "watchmaker" class and picked up an iron falx, which has 5 damage units.
How much damage should we take? 5 * 0,85 (15%) = 4,25 (4,3, if rounded up)
Now let's add our bonus. 4.3 * 1.25 (25%) = **5,3 - Is this our resulting damage?**
Are the mechanisms locusts and bells? Then it turns out that the bonus does not work :[
After all, the damage is 4.3. In the screenshots, I took exactly 1 hit and immediately took a screenshot.

### Screenshots

![2024-01-27_20-26-16](https://github.com/anegostudios/VintageStory-Issues/assets/51534323/eecde180-c5a9-4f36-91de-cac8b6e27ac8)
![2024-01-27_20-26-20](https://github.com/anegostudios/VintageStory-Issues/assets/51534323/8bedf869-6958-47d6-aa49-8e8b5661cf1d)
![2024-01-27_20-26-36](https://github.com/anegostudios/VintageStory-Issues/assets/51534323/c49c4c82-8bdf-4193-94b8-00358568d7f4)
![2024-01-27_20-32-09](https://github.com/anegostudios/VintageStory-Issues/assets/51534323/f8de8c4d-0a47-435e-94f1-a6c18ecf42eb)

### Logs

```Log```

**Comment by CookieBoy21** [comment]
This issue was fixed in v1.19.4-rc.1. I tested it as clockmaker class and damage bonus for mechanical enemies apply correct, for it I used iron falx. Before we had 4.3 damage and now we have 5.3.
<img width="1280" alt="Vintagestory Screenshot 2024 02 21 - 15 53 23 84" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/0d2450b1-34d5-42fa-b981-ed623ea8aafa">
<img width="1280" alt="Vintagestory Screenshot 2024 02 21 - 15 53 36 14" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/4a82b628-1d7a-44f3-8fb7-90aa60b28d82">
<img width="1280" alt="Vintagestory Screenshot 2024 02 21 - 15 53 40 08" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/416f20cb-ec89-4a30-a381-51dd8dea7cf3">
<img width="1280" alt="Vintagestory Screenshot 2024 02 21 - 16 23 00 21" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/2904efd0-f5d2-4cd4-86f1-249c0d90fc1f">
