### ISSUE TITLE
Structures can generate in saltwater and below mantle

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3564]
### Game Version

v1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The code for structure is not checking for saltwater. Also the underwater checks are insufficient. it's only checking the corners to my information. I'm guessing performance reasons. 

![image-12](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/a1a226e3-b1f7-45c8-adc9-247e3506f4c8)
![image-14](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/d7b003a8-9484-4bce-b5b0-f7c378f28f77)
![image-28](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/50642ce4-060f-4075-8fcb-35d032ee5c42)

### How to reproduce

You can use my mod betterruins or vanilla and fly around with oceans enabled. 

### Screenshots

![2024-02-02_23-48-56](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/209ff5f4-f12c-48ca-8e7e-8ffeb64040f7)
![image-25](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/0cfa0180-66bb-4a53-8446-86445c4fe6c8)
![image-13](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/734aa83c-096d-4e95-ace7-0c58e8527cb1)

### Logs

```Log```

**Comment by AreYSerious** [comment]
![2024-02-08_19-46-19](https://github.com/anegostudios/VintageStory-Issues/assets/100879715/ec55fd36-027e-4147-bd89-5749cbf5668e)

**Comment by Barhandar** [comment]
Underwater generation itself fits perfectly with "the world got scrambled" idea implied by the lore. The issue is generating things that should not be there - grass, regular water, etc.

**Comment by Barhandar** [comment]
IIRC the problem with "shallow" vs "not shallow" is that the game doesn't actually deal with saltwater correctly at all, as evidenced by [this comment](https://mods.vintagestory.at/show/mod/8969#cmt-19114 (the code checks for nonexistent "seawater" block rather than existent "saltwater"), besides lacking a check for water depth.

**Comment by AreYSerious** [comment]
Yeah with the the problem with the saltwater is why this issue has been posted.

The shallow water is bcs structures only get checked on each corner for performance reasons so the there is no water it will spawn that's why they can spawn in shallow water

**Comment by radfast** [comment]
I don't think the issue is specific to **salt** water, the code checks for any kind of water at the 4 corners.  Maybe seen more on high ocean worlds just because there is more, and more deep, water on such worlds.

The issue here is the checking code is buggy, it is checking at heights based on the centre position of the ruin, but in the 4 corners being checked, those checks may be inside rock, if the lake / seabed is uneven.  No water of any kind inside rock!    We can fix in 1.20 I think, simply by checking for liquids at a higher point on the structure - but this will require testing and tuning.  We don't want to lose the current behavior where vanilla ruins sometimes spawn underwater - it looks awesome in shallow lakes - but I can understand that surface ruins should not spawn **deep** underwater.

My current thinking: the liquid check should be at a random position between 3 and 7 blocks high on the structure: this will mean that structures will naturally be less and less likely to spawn, the deeper the water is, and nothing below depth 7.  Something like that.  Needs tuning.

**Comment by radfast** [comment]
Yep, something like that, needs testing for the structures with very deep cellars.

Meanwhile, the "below mantle" issue, is that seen in 1.19.4-rc.1 or later?   -rc.1 included code to fix structures attempting to generate off the map edge, I don't remember now whether we also check for below mantle

**Comment by AreYSerious** [comment]
It's pre 1.19.4 and it wasn't reported directly by me but by one of the mod users.
The structure is currently disabled in the mod bcs of the prior performance issues and the mantle issue (which is rare since it only can happen to words with either oceans enabled or low Worldheight.

I can try to test it in the future but I'm generally not using oceans...

**Comment by radfast** [comment]
I'll look at the mantle issue - though it may also be mitigatable using an appropriate `minY` value, see below.

You're right, the underwater generation issue will affect larger (wider) structures much more, as the 4 corners are more likely to be in rock/lake-bed not water.  But it will affect vanilla and will need careful testing - we want vanilla ruins to be able to spawn still in shallow water - so a fix for that will have to wait until 1.20, I'm afraid.

Meanwhile you should be able to mitigate underwater generation completely by setting `minY` on the appropriate group of structures in the `structures.json` config.  The default value is -0.3 if it is unset, I'm not sure why that default was chosen but in general we do allow surface worldgen (e.g. trees and grass) below sea level, to ensure that cave-mouths still have some vegetation - I don't really see the need for cave-mouths to have _ruins_, but there may be another edge case I have not thought of.   In your mod, you can set `minY` to 0 or above for all your surface structures, that would force generation only above sea level.

**Comment by AreYSerious** [comment]
I messaged radfast about this on dc dm

The minY doesn't work at all atm.

**Comment by Craluminum2413** [comment]
Is it ok if I label it as high priority?
