### ISSUE TITLE
boars will not eat dry grass from troughs

### ISSUE THREAD

**Issue by spongefreddie** [anegostudios/VintageStory-Issues#3589]
### Game Version

v1.19.3

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

--Dry grass introduced to troughs is not being eaten by boars anymore.
--At first I thought it was being caused by mods, but situation remains the same after removal of mods from both server and client, and server and client restart.
--I never noticed this before, but when you add dry grass to the trough, it lists which animals are suited to eat dry grass, and boars are not included in the list (never looked before, don't know if this is changed on purpose).
--Handbook still lists dry grass among the suitable food for boars.
--Some of the sows have eaten from 2 to 9 portions, but some sows haven't eaten any at all, so they're not all sated.
--I've checked, and it does seem that all the sows are ready to mate. Would that cause them to decline any more portions?

### How to reproduce

Put down a trough near a substantial amount of penned-in boars and fill it with dry grass.

### Logs

"Log"

**Comment by CookieBoy21** [comment]
It's look like this isn't bug, devs did it in intentional. They did it for balance because grass is extremely cheap and pigs are good source meat and fat also they have very number offspring. Unlike goats. I found it on discord in bug report, "Pigs no longer eat grass". 
![obraz](https://github.com/anegostudios/VintageStory-Issues/assets/132950198/5907b962-43bc-4352-95a8-e1a776aefdd2)
