### ISSUE TITLE
Pie disappears after baking

### ISSUE THREAD

**Issue by Bystrinko** [anegostudios/VintageStory-Issues#3731]
### Game Version

1.19.4

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

After baking the fruit pie (haven't tried any others), the pie just disappears.

### How to reproduce

You just need to make a fruit pie.  Put it in the bake.  Light it and wait.

### Logs

```Log```

**Comment by CookieBoy21** [comment]
It's happened to me too, but I think problem is that you can light pie for warm up oven. Normal you must warm up oven with fire wood before cooking, also you can do this same with bread dough but bread will not disappear but turn from dough into charred bread. Temperature will rais to 93C.
<img width="1280" alt="Vintagestory Screenshot 2024 03 17 - 13 54 39 63" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/88431223-da61-4aa2-8acc-f5c2d7dabbd1">
<img width="1280" alt="Vintagestory Screenshot 2024 03 17 - 13 55 09 23" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/e6242161-4f46-42df-9e3e-1d1091743d55">
<img width="1280" alt="Vintagestory Screenshot 2024 03 17 - 13 55 50 36" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/49682752-8cdf-4d41-acd5-659281c269b8">
<img width="1280" alt="Vintagestory Screenshot 2024 03 17 - 13 56 21 97" src="https://github.com/anegostudios/VintageStory-Issues/assets/132950198/71835de0-5fea-41f7-8656-6d5738351413">

**Comment by pingouyn** [comment]
Happened to my wife too (new player) because the oven tooltip is not explicit on that topic.
The in-game help page says exactly what to do with the clay oven but since its usage mechanism is not similar to that of the firepit (other cooking area) it wasn't obvious to her.

We either need to not be able to insert anything else than firewood in the clay oven when it is empty (similar behaviour to the bloomery whereby quartz has to be inserted before fuel for instance), or the clay oven tooltip needs to be adjusted to request adding firewood first.

**Comment by NinaraMamiko** [comment]
Had a pear pie disappear in oven when the pie went from partially cooked to cooked. Was able to pull it out. Crust and top were two different grains (not flax) and i don’t remember the pattern i had for the top.

**Comment by Craluminum2413** [comment]
Closed due to inactivity
