### ISSUE TITLE
[Mac] Thai characters that should display on another character takes full character space.

### ISSUE THREAD

**Issue by munkeawtoast** [anegostudios/VintageStory-Issues#3736]
### Game Version

1.19.4

### Platform

Mac

### Modded

Vanilla

### SP/MP

None

### Description

Using same font family: Tahoma

Another problem that I suppose is caused by this bug:
The word หนึ่ง in setting above First person mode FoV, there are two characters "ึ" and "่" (without the ring thing if you see the ring) that should be stacked on น but "่" is stacked on the space after "ึ"

Another bug? that i suppose is the same bug:
In some fonts like Thonburi (Thai macOS UI font) instead of displaying correctly with a space behind, it displays the version with the ring with the characters on (to show that it's supposed to have a parent character to be on)

### How to reproduce

Type text in language that has stacking characters or switch game's language to it.

### Screenshots

Mac (abnormal):
<img alt="macOS settings screenshot with Thai text display" src="https://github.com/anegostudios/VintageStory-Issues/assets/69665908/b3719558-f5ae-49a2-ba78-e129499bacdd">

Windows (normal):
![Windows settings screenshot with Thai text display](https://github.com/anegostudios/VintageStory-Issues/assets/69665908/74a2b02a-70ad-4a05-9f6f-65456ead6013)

Another bug:
<img alt="Screenshot 2567-03-19 at 20 57 49" src="https://github.com/anegostudios/VintageStory-Issues/assets/69665908/067a54cf-942c-4023-88d3-84103b09fc79">

**Comment by radfast** [comment]
Can you try setting these settings different on a Mac, in `clientsettings.json`:

    "defaultFontName": "sans-serif",
    "decorativeFontName": "Lora",

Especially the "defaultFontName", you should set it to a good Thai characters font on Mac.

In Windows (in game version **1.19.5**) the game will auto-switch to a good font (Leelawadee UI) when you choose Thai language setting.  You can set back to another font by manually editing `clientsettings.json` if you prefer.

On Mac the developers did not know the best font name to suggest for Thai characters - you can suggest one if you want, and we can try it :)   Best if it is a font which comes with the OS as standard, or else one which is so common that 99% of players in Thailand must already have it

**Comment by munkeawtoast** [comment]
I've tried changing it to all the system fonts and also ones I installed. I'm pretty sure that the font rendering system's to blame and not the fonts itself. Actually the exact same problem also exist in Minecraft to this days in every OS.

It might not be much but I once used [this mod](https://github.com/secretdataz/ThaiFixes-Fabric) in the past to fix the issue. I've read into the code and it fixes by adjusting each Thai characters position manually so in case the problem arises in other languages this might not be the way to go.

As for the best looking font. I've tried every system fonts. and I think `Thonburi` looks the best and has the same style as Leelawadee's. as for decorative font, also Thonburi. Here's the "what it should look like in theory" comparison.
<img width="1662" alt="ภาพถ่ายหน้าจอ 2567-03-23 เวลา 01 09 32" src="https://github.com/anegostudios/VintageStory-Issues/assets/69665908/da81ee74-6c5e-4683-9e6e-9a37e9a0bea0">

and here's the in-game comparison, still bugged but i tried getting it to show the least bugged word. looks good to me.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/69665908/3ef6a758-8781-4b61-b460-c1bc809281b6)

**Comment by radfast** [comment]
I've looked at this some more. I would see these as issues to raise with Apple, or else with the makers of the open-source font rendering library we use ([Cairo](https://github.com/zwcloud/CairoSharp/tree/master)).

If VintageStory is producing correct output in the Thai language in Windows (and in Linux) but the exact same text is bugged on Mac due to the diacritical marks being wrongly positioned, then I think the issue is not on our side.

How is this issue normally resolved on Mac in other software?

I don't thing we can use **Thonburi** at all, due to the ring issue - looks far worse, many words are bugged.

Another possible solution would be to produce an entire second Thai localization omitting any characters which have **two** diacritics, so in your example omit "่" in the cases where it should be double-stacked without another diacritic.  Would that be acceptable?  Surely it would make little or no visual difference, everyone would still understand what is meant?

I suspect at its root looking at the way Unicode deals with compound characters (look at the difference between Normalization Form C and Normalization Form D, i.e. composite characters or combining sequences).  [Further reading](https://www.unicode.org/reports/tr15/tr15-25.html)  But as above, this is something to be implemented either by Cairo or by OS-X when rendering the Thai language, something may be wrong in their pipeline.

_Possibly_ it's as simple as the font (e.g. Leelawadee UI) not containing a composite character with both diacritics.  If someone made a font with the correct composite character then all would be okay.
