### ISSUE TITLE
Cooling Ingots With Watering Can

### ISSUE THREAD

**Issue by Carltoffel** [anegostudios/VintageStory-Issues#375]
Would be a nice detail. Necessary change: right clicking on mold with watering can does not work yet.
![scrot_002](https://user-images.githubusercontent.com/33249047/75162719-423ab300-571e-11ea-9500-6cd275e43e6a.png)

**Comment by Angelnoir** [comment]
This wouldn't be accurate. 
In real world, if you melt ore you basically want to achieve 2 things.
1. Removing Impurities 
2. Getting a quite homogeneous atomic structure to work with
For 1. you need high temperatures to separate and remove the slag. For 2. you need to cool down the metal steadily to sort the very chaotic atomic structure after melting.

If you suddenly cool down metal from around 800-1100°C with 20°C hot water(you would definitely need more than 10 liters from the watering can) two things would happen.
First the water (the h2o parts of it) would instantly vaporize, leaving the mineral elements on the surface. Secondly the rapidly cooled metal would solidify while in a rather chaotic atomic structure. The resulting metal would be way more fragile.

This is different from heating the metal to red glowing and working it on an anvil, because in this case you compact the sorted atomic structure (creating shiftings) and need rapid cooling to "save" your now more stable structure because the metal wants to get back to its original atomic structure. 

You could cool it with water, after the atomic structure has formed and the metal isn't melted anymore, so for example below 700°C. 

The mold is the next problem, the fast temperature drop would lead to cracks in the mold making it unusable for future use.

Since they try to be somewhat accurate with their stuff, they would need to implement that you can brake your mold and ruin your metal when applying too much water too fast and stuff.
And to be strict they would also need to implement the fact that metal pieces only formed in molds aren't as durable as forged ones, because the metal wasn't mechanically hardened.

**Comment by Carltoffel** [comment]
Honestely, I think what you described is way over the level of realism the game is aiming for. Before they would be this accurate they had to implement overcooking food, burning blocks next to campfires, hurting yourself while dealing with molten metal and so on.

In my opinion it would be more consistent to cool metal with water from a watering can, because rain is cooling down fireplaces, too.
It doesn't matter if it is useful in real life, pouring water over glowing metal should cool the metal an vaporize the water.

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
