### ISSUE TITLE
Moose won't deal any damage

### ISSUE THREAD

**Issue by MonsterHorns** [anegostudios/VintageStory-Issues#3772]
### Game Version

1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Moose will charge as if attacking, but the impact just pushes the player with no damage dealt, the moose then runs away and charges again with no damage as well. The world settings for animal attacks are default. Other animals like wolves and boars deal damage normally. Screenshots attached.

### How to reproduce

1. Find a moose
2. Stand near the moose
3. Observe no change in health

### Screenshots

![2024-04-03_16-54-38](https://github.com/anegostudios/VintageStory-Issues/assets/80121766/15dd663f-d3f2-465c-80dd-f4414ac2ab00)
![2024-04-03_16-54-50](https://github.com/anegostudios/VintageStory-Issues/assets/80121766/6689e965-f7c2-464c-b686-5803fcd914ad)
![2024-04-03_16-55-03](https://github.com/anegostudios/VintageStory-Issues/assets/80121766/b2ece7a4-f9e1-4f6b-94b3-408de44c78ae)

### Logs

```Log```

**Comment by malnaur** [comment]
Aggro the moose and it will cause damage :) Passive moose do not.

**Comment by MonsterHorns** [comment]
Yes, if you hit the moose it will deal damage, however I'm pretty sure they're supposed to be always aggressive, and their movement suggests that too. Unless they are just really obsessed with sniffing players.

**Comment by malnaur** [comment]
They're just friendly. Be grateful something in the game is not out to kill you :)

**Comment by pingouyn** [comment]
Currently moose are always charging the player as if wanting to attack them but they do not in the end.  The issue is, whilst placing or collecting blocks you will at some point hit them by mistake and then they will start becoming aggressive when you least expect it.  Extremely annoying.

Their normal behaviour should either be neutral and not rush you, or fully aggressive - rush and hit you, but surely not a bit of both at the same time.
Whichever of these 2 behaviours the devs have in mind if fine to be honest.

**Comment by VallenFrostweaver** [comment]
Can confirm that this is an issue. Moose will charge, nudge the player, retreat, repeat - over and over and over - making this easy to exploit and not what a moose would do to boot. This is not intended behavior.

**Comment by malnaur** [comment]
But it's funny as heck. They are like giant puppies. I will be sad to see it 'fixed'.

**Comment by Craluminum2413** [comment]
Fixed, no idea when
