### ISSUE TITLE
Locust nests don't drop Jonas parts. Stack randomizer doesn't work

### ISSUE THREAD

**Issue by Guimoute** [anegostudios/VintageStory-Issues#4013]
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Locust nests have a 100% chance to drop one Jonas part in theory. In practice, I never see them drop one. Strangely, corrupt sawblade locusts do drop the part every time as intended.

My character is a hunter in case that changes anything in terms of drops.

### How to reproduce

Break a locust nest.

### Screenshots

https://github.com/user-attachments/assets/f08a55a3-145b-419a-b53b-dd2b9eb9325a

https://github.com/user-attachments/assets/2b21d93d-4527-420b-a9c4-3c3d8f1f5b47

### Logs

```Log```

**Comment by pizza2004** [comment]
According to the JSON code that stackrandomizer-alljonas item does not have a 100% chance of dropping.

The JSON says this `{ type: "item",	code: "stackrandomizer-alljonas", quantity: { avg: .1, var: 0 } }` which is perhaps more like saying a 10% chance of dropping a single one of these.  It's not exactly the same as 10%, but I hope that illustrates the point at least.

What I am guessing is that the 100% being seen (I'm guessing because of a mod, but I haven't checked to be sure) is actually talking about a 100% chance that when dropped it will pick one of the items from that list to spawn.
