### ISSUE TITLE
Unable to launch on Linux 

### ISSUE THREAD

**Issue by Zolkennn** [anegostudios/VintageStory-Issues#4096]
### Game Version

v1.20-pre.1

### Platform

Linux

### Modded

Vanilla

### SP/MP

None

### Description

When launching the game on the freshly installed game on my Linux computer, the game shows me a black screen. I can't launch any world or do anything.

### How to reproduce

1) Install the game on a Linux Machine (Maybe a more specific for my distro see screenshots)
2) Run the game

### Screenshots

![image](https://github.com/user-attachments/assets/dfba1245-0917-415d-a21d-0d730472f48e)
![image](https://github.com/user-attachments/assets/2578ef08-b363-428a-abd2-d75921611ff7)
![image](https://github.com/user-attachments/assets/9286457a-34b4-477b-bf18-451bc2479b10)

### Logs

```Log```
[client-debug.log](https://github.com/user-attachments/files/17048541/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/17048542/client-main.log)

**Comment by Th3Dilli** [comment]
thank you, will be fixed with next release

till then you can also fix it for yourselve by

opening file `assets/game/shaderincludes/fogspheres.ash`
line 12
and change
`if (fogSphereQuantity == 0) return 0;`
to 
`if (fogSphereQuantity == 0) return 0.0;`

that should do it for now

(lets keep this open for now till we release the new version)
