### ISSUE TITLE
[Worldgen] Regeneration doesnt allow a set position for the RA

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#4119]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

/setstorystrucpos resonancearchive <x> <y> <z> true
then 
/regenr 7

doesnt result in the RA being there

I have tested in 1.19 latest 

there it works

might be related to the new seed related changes ? @Th3Dilli

**Comment by Th3Dilli** [comment]
hmm I see, there is multiple issues, unrelated to the seed determinism changes

1. it does not work on a fresh world, in a new world (joined first time) it always respawns them where its in the storystructure.json
2. the command output is a bit missleading
you need todo `/setstorystrucpos resonancearchive p[] true`
to spawn at player pos or any other position you like

then you can use /wgen regen 7 or /wgen regenr 7 both work
regenr only spawn a different rockstrata

so for what you need you only need to join the world again for now and it should work

**Comment by AreYSerious** [comment]
Ok I will try with rejoining

I used the true in the command yeah.

**Comment by Th3Dilli** [comment]
as long as you only have 1 story location it should work other wise it will move them to the same location which may only generate the one that appears first or both (did not test)?

but you will have to close the game at least once still also in next version for now, if we change that i will let you know here

will be fixed in next version
