### ISSUE TITLE
Beehive hatches have opposite effect from what they should

### ISSUE THREAD

**Issue by pandapants200** [anegostudios/VintageStory-Issues#4178]
### Game Version

v1.20.0pre.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Not exactly a bug but a problem with the mechanics. Opening hatches on the beehive kiln leads to more oxygen and darker ceramics. However this is opposite of how oxygen should affect ceramic. A oxygen starved reduction environment produces the darkest pottery which can be dark brown, gray, or black in color. The presence of oxygen in a kiln brightness the color because it reacts with the iron present in the clay.

### How to reproduce

Mechanic problem

### Screenshots

![image](https://github.com/user-attachments/assets/509ff16f-0848-46ba-877e-a290db893e94)

### Logs

```Log```

**Comment by Marcafk** [comment]
This lines up with what I saw when researching the blue /black almost clinker bricks that a certian english town is famous for, they were produced at the highest temperature in a very reduced environment.

**Comment by RedramVS** [comment]
Both things are true.  Higher temperature creates darker colors, at the dark end.  While reducing atmosphere can create lighter colors, at the light end.  It was felt that it was better to keep the mechanic simple and straightforward, if somewhat unrealistic in some aspects.   People are quite familiar with the notion of things cooked at higher temperatures getting 'burned', i.e. darker.  So since this is a more intuitive method, we went with it.   
We do hope to revisit the mechanic again in the future, once the temperature system as a whole is reworked.  We can consider bringing more nuance then.  But for now the system accomplishes what we wanted: many finished product colors without having a ridiculous number of colors of clay spawning, in a simple to understand and execute system.
