### ISSUE TITLE
Sailboat's 'Prow Port Storage' Cannot be Used, and 'Starboard Port Storage' Does Not Exist

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4206]
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The prow port storage on the sailboat cannot be used to store anything, and the starboard side is missing a prow storage space.

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Anchor can be put there
![image](https://github.com/user-attachments/assets/9684b6bb-02e0-492c-b31b-366cd9ad243b)

**Comment by ifozz** [comment]
Ahh, gotcha. Didn't know that. :)

**Comment by RedramVS** [comment]
Ya this is not a bug per se.  The prow spaces are tapered so we can't use any regular containers there.  The location was named generically so that other things might someday be able to be put there, other than just anchors.  The placement of the anchor here is currently mentioned in the sailboat entry in the handbook, but I will add handbook text to the anchor entry as well, pointing out that it can be stowed there.
