### ISSUE TITLE
Text with key "Created by" is used two very different places making translation difficult 

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4408]
### Game Version

1.20.0-pre.9

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

In the process of translating to Danish, I found that the string **Created by** with the key `Created by` is used in two (maybe more) very different places.

It is used in the _Modify World_ window for the section stating who created the world.

Then, it is used in the _Survival Handbook_ pages as the title for the section describing how items or blocks are created.

This is not a problem in English, but in Danish, we need two different translations.

In _Modify World_, we would say **Oprettet af**, and in _Survival Handbook_, we would say **Fremstilles via**.

A side note: It would really be great if you used keys that describe where the string is used (which you do on many strings) and not just the string itself as the key. It would make translation easier. :-)

### Screenshots

![createdby1](https://github.com/user-attachments/assets/30a406e2-0fd1-4f52-9790-bcdb7bbf8932)
![createdby2](https://github.com/user-attachments/assets/842194ad-edb4-438d-8987-6f23a9042e2d)

### Logs

```Log```

**Comment by tannyl** [comment]
The string used in the handbook page is found here: https://github.com/anegostudios/vssurvivalmod/blob/47b8a492f77c53ad121980bcce9f0778791fdbb5/Systems/Handbook/CollectibleBehaviorHandbookTextAndExtraInfo.cs#L876 (translations with `Lang.Get` happens inside `AddHeading`)

The problem could be fixed with something like this to keep it inline with other handbooktitles and strings used in this section:
`AddHeading(components, capi, "craftinginfo-handbooktitle", ref haveText);`

And then adding to the translations:
`"craftinginfo-handbooktitle": "Created by"`

**Comment by radfast** [comment]
I am reluctant to change existing translation keys (unless to signify substantial change in the meaning/usage) because that will be a retrograde step for other languages who have already translated the key.

In this case I think the best thing is to change the key for the _Modify World_ GUI, because that is not so commonly seen (and I can do a fallback test there).

**Comment by tannyl** [comment]
@radfast I understand the reluctance, but I am 100% certain that people translating would welcome gladly any changes that makes translation easier due to better context. I have seen many messages on crowdin that asks for context in some form (but never any answers from devs), becuase they simple don't know how to translate correctly just based on the English words themself.

Also Crowdin has a "time machine" function which remembers old translations even if they have been removed (or had keys changed) and re-added so it's easy and fast to add them back again.

I am 100% sure that people helping with translations are more then happy to accept to translate a string again if you started fixing all the translations keys and giving them a better context.

So please reconsider this stance, as it will make translations so much easier for all the languages that are still missing many translations and might even fix errors along the way in those that have been translated already.

**Comment by MyraMidnight** [comment]
the translation key is crucial context, and sure people might have to retranslate something if you change it into something useful, but it saves headache of trying to figure out the context for yourself. `Created by` and `Created with` are good examples, as well as any short string without context like `on` .

Using the string itself as it's own context isn't ideal, specially if you want to update the string itself, then it doesn't match, I've seen so many long strings that use themselves for context... and the old dialog for merchants, love how the new NPC interactions have a context so you can just look it up and translate the whole chain of dialog, instead of just hoping you run into the correct strings along the way.

Translation should not be a game of "find the context by digging through the code" and it's even harder to do just that if there is no context. And when going over a translation to make sure things actually made sense, and you see a very out of context string and wonder "why the heck did I translate it like that, where can I see if it fits?". It's a bit slow to make translator play full game and hopefully find every detail to text the context every time.

changing from messy early practices to something properly organized can be painful, but sometimes growth can be painful.

**Comment by RomainOdeval** [comment]
> @radfast  I am sure that people helping with translations are more then happy to accept to translate a string again if you started fixing the translations keys and giving them a better context.
> 
> So please reconsider this stance, as it will make translations so much easier for all the languages that are still missing many translations and might even fix errors along the way in those that have been translated already.

I agree with all those statements.
Messy early practices continue to be bother for translators and we will be thankful to change them if the only cost is to re-translate them.

**Comment by MyraMidnight** [comment]
Yeah, actually ran into this when reviewing the translation. I tried to translate 'created by' as 'created in the following ways' for handbook and that does indeed look super weird when it's referring to the player who created the world. 

Please do not reuse strings like that when you want things to be translatable, not all languages refer to things in the same way. Even if I had kept it simple, 'created by <means>' and 'created by <player>' is not as identical when translated.

**Comment by tannyl** [comment]
@radfast in the patch notes for rc6 we have the following line
`API Tweak: new Lang.GetWithFallback(key, fallbackKey) method to allow us to replace an existing lang key seamlessly`
Is this in response to the above? :1st_place_medal: 

No matter what, that is a great solution to create a smooth transition from the old "the text it self" keys to contextual keys.

I do hope you treat the old keys as deprecated and after some versions after they have been replaced by new contextual keys, remove the old keys. Otherwise the amount of duplicated translations will just grow and grow. :smiley:

**Comment by radfast** [comment]
I agree that is a good idea. Yes, this new method in the code is intended to allow for a smooth transition in appropriate cases. I think we do not want to break a language which is already 100% translated.

However, I am expecting that after 1.20.0 is stable I will be working exclusively on other aspects of the game (most likely performance), so it will be others in the dev team looking at localization in future.  Primarily you need to persuade tyron himself that this is an area which deserves a rolling programme of key replacement.
