### ISSUE TITLE
3 masks have graphic bug.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4416]
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Cat mask, festive cat mask and marketeer mask have graphic bug.

### How to reproduce

Just wear any of this masks.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 11 02 - 02 01 29 26" src="https://github.com/user-attachments/assets/4290a8b1-803d-455f-81f9-d8cb4da8f0a8">
<img width="1280" alt="Vintagestory Screenshot 2024 11 02 - 02 01 32 98" src="https://github.com/user-attachments/assets/2554fa8b-cebf-4bfa-961e-186a26cc93da">
<img width="1280" alt="Vintagestory Screenshot 2024 11 02 - 02 01 37 79" src="https://github.com/user-attachments/assets/bf2045e3-d873-486f-806e-2afe10859f20">

### Logs

```Log```

**Comment by RedramVS** [comment]
The issue here is related to the festive cat mask having an animation.  Because the ears of all 3 of these masks have the same name, that one animation is influencing all 3 mask ear sets, even though the other two masks do not have animations.  I tried renaming the elements on the fancy cat mask ears, which isolates the issue to that mask, but then causes a lot of error log spam.  Probably will require Tyron and/or Ambroise to address.

**Comment by tyronx** [comment]
thank you for the report, will be fixed next release
