### ISSUE TITLE
Flour not considered grain. 

### ISSUE THREAD

**Issue by TheUSDoctor** [anegostudios/VintageStory-Issues#4427]
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Flour is treated as any other item instead of grain, meaning it spoils faster in storage vessels. 

### How to reproduce

see screenshots, since it is simply re-creatable by placing and removing flour from any storage. 

### Screenshots

![2024-11-02_21-59-27](https://github.com/user-attachments/assets/cc9168bf-a5d7-44b3-9262-9057db1d855d)
![2024-11-02_21-59-21](https://github.com/user-attachments/assets/ff5531bf-4639-4f45-b06d-25a54ab79828)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Do you mean it was "1.3 years" before you put it into crate/chest, then it became "1.7 years" after you take it back?

**Comment by RedramVS** [comment]
Flour has no food props and cannot be eaten by itself.  I'm guessing this is intentional. It presents the player a choice between storing it longer in grain form, or shorter already ground into flour.  As opposed to just mass-grinding all the grain and storing it as flour.  But I'll check with the team.

**Comment by RedramVS** [comment]
working as intended
