### ISSUE TITLE
Visual bug: Various mechanical parts (axles, gears, rotors, sails, etc) not rendering

### ISSUE THREAD

**Issue by MFKZT** [anegostudios/VintageStory-Issues#4630]
### Game Version

v1.20.0-rc1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In both single and multiplayer vanilla worlds, placed mechanical components only render their non-moving parts. The issue persists through rebooting the PC and reinstalling the game. Lots of OpenGL errors can be seen in the log. Using Windows 11 with a Radeon RX 580 8gb GPU.

### How to reproduce

Place a gear, axle, transmission, clutch, rotor, etc. If you replicated the bug the moving parts should be invisible.

### Screenshots

![image](https://github.com/user-attachments/assets/4a446682-93d3-478f-a3f0-44b3f63e995b)

### Logs

[client-main.log](https://github.com/user-attachments/files/18054029/client-main.log)

**Comment by Craluminum2413** [comment]
Try reinstall the game

**Comment by MFKZT** [comment]
> Try reinstall the game

> The issue persists through rebooting the PC and reinstalling the game.

**Comment by radfast** [comment]
The root issue here is a shader compile error seen in the log;

     [Error] Shader compile error in instanced.fsh ERROR: 0:763: 'applyFogAndShadowWithNormal' : no matching overloaded function found
     ERROR: 0:763: 'assign' :  cannot convert from ' const float' to 'layout( location=0) out 4-component vector of float'

So what to do about this?

Assuming that this is, as stated, a fresh install of the game and you have not manually patched or edited anything - please triple check with an open mind - then this is 99% likely to be a graphics driver issue. The reason I think this is the same shader code works for everyone else, including other Radeon owners. OK I didn't do a survey for all Radeon models, but RX580 is not too old and was a great GPU on release, and it states it supports OpenGL 4.6, so it _ought_ to be okay.

First thing to try is update your graphics drivers to the latest  (If you also have the option of switching to other graphics hardware - a few people do - then try that too.)

Second thing to try is in Settings from the main menu, before starting the game, switch off **SSAO**.   You can also try turning down a few other settings though other settings are less likely to make any difference here.

If neither of those steps fixes it, then there are two main possibilities:
* you've found a bug in your specific card's OpenGL shader support which ATI have not yet fixed  (not too likely, as the same graphics driver code is mostly re-used on other cards too)
* we have written a shader in a way which, while technically correct, doesn't compile on some specific ATI cards due to idiosyncrasies in its OpenGL implementation  (a.k.a. bugs)

I've checked the shader code here in 1.20-rc.1 and it looks totally okay to me, and there is an extremely similar line of code in other shaders including `chunktransparent.fsh` and `chunktopsoil.fsh`, and those two have not errored, so I'm really struggling to see what the VS dev team can do here.

**Comment by radfast** [comment]
Also an important question for you: have you played Vintage Story on this same PC and GPU before our version 1.20-rc.1?  Were you able to see mechanical power devices properly in older game versions? (Which?)

**Comment by bonenaut7** [comment]
I've researched once very strange behavior on AMD RX4xx & RX5xx with specific driver versions, i'd like to advise to test this issue out with another version of drivers, specifically Adrenalin 22.6.1.

Back then there was a huge problem with games that was using already deprecated OpenGL Display Lists(not related to this issue, but as far as i know after that more than for an year problem was existing and there's a ton of messages on AMD forums about that exact issue), so maybe driver roll-back could be also helpful.

**Comment by MFKZT** [comment]
Thanks for the response. I tested again on the latest AMD driver version with SSAO off and that didn't fix it. However, after reinstalling the game *again* (in this case updating to rc-5) the issue was fixed. I reinstalled twice before making the OP, so I don't know what was different this time. Just for good measure, I tested again on the rc-1 version and it was still working as expected. Apologies for reporting likely user error as a bug.
