### ISSUE TITLE
pies disappear.

### ISSUE THREAD

**Issue by snipermonkey2** [anegostudios/VintageStory-Issues#4672]
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

when i wanted a pie it just disappeared in front of my eyes

https://github.com/user-attachments/assets/1d761376-91f1-4807-9939-9a725753c3c7

### How to reproduce

just do the procedure to cook a pie in the normal order

### Screenshots

![image](https://github.com/user-attachments/assets/f8ea9227-3c50-447e-be12-b8f4511fc82b)
![image](https://github.com/user-attachments/assets/709e6a22-f713-46fc-abec-cc06a854ff7c)

### Logs

```Log```

**Comment by pingouyn** [comment]
As seen in #3731 and #2833.

**Comment by pizza2004** [comment]
This looks like what happens when you put a pie in the oven and light it on fire and use it as fuel.  Just to be clear, did you preheat the oven with firewood and put the pie in and light the pie on fire and still have this result?

**Comment by pingouyn** [comment]
I commented in 3731 because it happened to my wife too.
In 3731 and in this very bug report you can see flames in the oven on the images provided.

What most certainly happens is new users naturally think the oven works like a cooking pot or a crucible, i.e. food first then light it up.
The oven help page explains what to do but not the tooltip.

The thing is even though there is no bug as such, it's not clear enough to new users and if you already have more than 3 bug reports it most certainly affects many more new-ish players.

The quicker fix would be to amend the tooltip imo.

**Comment by pizza2004** [comment]
I agree, I just wanted to be sure it was what it looked like to me.  I remember burning my first batch of bread this way and my BFF destroyed her first pie.  Immediately after I remember thinking, “Duh, this is an oven, of course I have to pre-heat it” but I do think a tooltip would be helpful.

**Comment by pizza2004** [comment]
Fixed in next release.
