### ISSUE TITLE
Specific ruins have uninteractable chests

### ISSUE THREAD

**Issue by TheCastleKeeper10** [anegostudios/VintageStory-Issues#4704]
### Game Version

v1.20.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

A specific above ground ruin type, with the aged tree growing through it - see image, has a chest that cannot be interacted with. 

The screenshot is actually from a certain area that had three of the same ruin nearby and this was true for all of them. While this is in v1.20.0 now, this was also an issue for previous/stable versions. 

### How to reproduce

1. find this ruin type
2. attempt to open the chest 

### Screenshots

![Screenshot 2024-12-14 222306](https://github.com/user-attachments/assets/9d629066-f35f-47d3-bb23-595958c90928)

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Is it 1.20-rc.4?

**Comment by MtSheepFarm** [comment]
This has been a feature of those ruins since they were added I think. The collapsed chest will not open if it does not have loot, so I've just assumed that particular structures chest did not have a lot table. Maybe someone else has had a different experience, but all through 1.19 I didn't find a single one that had anything.

**Comment by RedramVS** [comment]
Ya looks like this one was missing a randomizer entirely.  We'll put one in.   Loot randomizers do land on 'nothing' sometimes, but it's definitely suspicious if they come up empty multiple times.  Though not necessarily unintended in larger ruins and dungeons.
