### ISSUE TITLE
rc.5 Bee Hive Kiln becomes invalid

### ISSUE THREAD

**Issue by Mephis00117** [anegostudios/VintageStory-Issues#4721]
### Game Version

v1.20.rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

downloaded rc.5 and noticed my active bee hive kiln was no longer receiving heat and the entire structrure showed as invalid. Tried replacing refractory bricks but they also showed as invalid. Only the door appeared to be a valid structure.

Loaded rc.4 back in and the beehive kiln was valid again.

### Logs

```Log```

**Comment by tannyl** [comment]
I can confirm this happening for me as well after going from rc.3 to rc.5.

**Comment by pizza2004** [comment]
I believe this is because they got the regex for the structure slightly wrong inside the beehive kiln door JSON.  They also missed adding a heat resistance value to the new fire clay door.
<                "@(claybricks-good-fire|refractorybricks-good-tier*)": 1,> should be this: <                 "@(claybricks-good-fire|refractorybricks-good-tier.)": 1,> instead if I understand regex properly.

**Comment by tyronx** [comment]
thanks for the report, this is fixed for next release
