### ISSUE TITLE
Tutorial step numbering broken on steps after 3

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4726]
### Game Version

1.20.0-rc.5

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The first 3 steps of the "First Steps" tutorial are numbered from 1 to 3. But this lacks in all following steps. See screenshot below.

The reason for this is simple enough. The first 3 steps are handle by `Systems/Handbook/Tutorial/TutorialStepBase.cs` and the numbering is added in the function `RichTextComponentBase` at https://github.com/anegostudios/vssurvivalmod/blob/d42d85eaef4fa3cdbea304fc0e74663c52c2985c/Systems/Handbook/Tutorial/TutorialStepBase.cs#L97

But all the following steps are handled by `Systems/Handbook/Tutorial/TutorialStepReceive.cs` and the text is processed in its `RichTextComponentBase` here https://github.com/anegostudios/vssurvivalmod/blob/d42d85eaef4fa3cdbea304fc0e74663c52c2985c/Systems/Handbook/Tutorial/TutorialStepReceive.cs#L88-L104  which does not use the `tutorialstep-numbered` string when building the final text.

Also we have some left over code there that is not used anymore after changes most likely due to #4623 that could be removed (I love optimizing), so we could end up with something like:

```
public override RichTextComponentBase[] GetText(CairoFont font)
{          
    string vtmlCode = Lang.Get("tutorialstep-numbered", index+1, Lang.Get(text, rwatcher.QuantityAchieved >= rwatcher.QuantityGoal ? rwatcher.QuantityGoal : rwatcher.QuantityGoal - rwatcher.QuantityAchieved));

    return VtmlUtil.Richtextify(capi, vtmlCode, font);
}
```

And the translations with key `({0}/{1} collected)` could be removed from the translations files as well since it is not used anymore.

### Screenshots

![Screenshot from 2024-12-17 22-47-58](https://github.com/user-attachments/assets/38133acd-881d-403c-9eb3-5af5a1a4e552)

### Logs

```Log```

**Comment by radfast** [comment]
Thank you, it will certainly look better in the Handbook with the 4. 5. 6. etc. added.

I think best not to remove key `({0}/{1} collected)` as it's possible we will decide to reinstate that in some of the steps in the First Steps Tutorial, or in some later tutorial to come in future.  More generally still, the entire tutorial system is a bit of a placeholder at present I would say, put together quickly because we didn't have one at all, and that's also why it still had a few bugs at the start of the 1.20 cycle. I would imagine the long-term goal is a tutorial system where tutorials can be written in pure JSON.
