### ISSUE TITLE
Audit System not reporting Sail Boats

### ISSUE THREAD

**Issue by Darkx352** [anegostudios/VintageStory-Issues#4757]
We had a theft on the server. When I pulled the audit system, nothing was reported for sailboats. 
Even if you place a chest on a sailboat, nothing can report what was moved in or out of the chest. Or that the chest even exists in the audit system. This has created a black hole in the audit report. 

Sailboats can also be removed from claims and do not indicate player ownership.

**Comment by radfast** [comment]
Sailboat chests are currently logged, only the name is a bit weird.  Example:

    [Audit] radfast left clicked slot 0 in mountedbaginv-12-3666. Before: (mouse: empty, inv: 1xWooden chest), after: (mouse: 1xBroken chicken egg, inv: empty)

I'm looking at logging also when that inventory is open and closed to put a position on it

**Comment by radfast** [comment]
Sailboat audit logging now added to next upcoming version 1.20.0-rc.7

> Found a another audit log not reporting. When a player tosses something on the ground it is reported Player placed item on the ground. But it does not show what player picked items up from the ground. "22.12.2024 18:05:26 [Audit] Cryptidd moved 1xfloralzonescaperegion:flower-leucadendronsalignum-free from hotbar-i432p1OLXfx2xa9bz4AiVH70 to ground-i432p1OLXfx2xa9bz4AiVH70"
> 
> Where this would be useful is if two parties are doing a trade and tossing items to each other and a party runs through them and collects the items there would be no log of that. .

That seems too minor / too much of an edge case to audit.  In normal gameplay, players are regularly picking up items from the ground regularly and in potentially large numbers - breaking and harvesting blocks, etc.

I think if two players are trading by tossing items on the ground, what they toss down is logged so the server has a record. If a third player comes at that exact moment and picks up the items, instead of the intending player picking them up, then the players involved will see it so they will know the culprit. But more generally seems like a normal risk of multiplayer. If players want to do trades without interference, go to a more private or secure place. In general, I think if you toss items on the ground, they become public property and nobody is doing anything 'wrong' by picking them up.
