### ISSUE TITLE
Cannot type /waypoint add color title

### ISSUE THREAD

**Issue by Zaldaryon** [anegostudios/VintageStory-Issues#479]
**Game Version:** 1.12.9-rc1
**Platform:** Windows 10
**Modded:** Yes (VSHUD)

### Description
Everytime I try to add a waypoint via command line it says "No text supplied. Syntax: /waypoint add [color] [title]". Also "Color may be a known .net color or hex number"

### How to reproduce
1. Type /waypoint add blue Lapis
2. The message appears and no waypoint is saved. Alternative attempts with same result:
3. /waypoint add 'blue' Lapis
4. /waypoint add 'blue' 'Lapis'
5. /waypoint add "blue" "Lapis"
6. /waypoint add blue "Lapis"
7. /waypoint add "blue" Lapis
8. /waypoint add #0000FF Lapis
9. /waypoint add "#0000FF" Lapis

### Expected behavior
Waypoint to be marked. The big map click and save works fine, though.

**Comment by copygirl** [comment]
Tyron [commented this](https://github.com/anegostudios/VintageStory-Issues/issues/477#issuecomment-601062252) in another issue:

> ooooooh, this crash would happen if a way point position is null, which would indeed happen when you connect to a v1.12.8 server with a v1.12.9 client, due to the fact that the /waypoint add command syntax changed.
In other worlds this will be fixed in v1.12.9. That version now requires the server to be on v1.12.9
>
> As a double safeguard, prevented the server from adding invalid waypoints as well now.

I will close this for now, as it should be resolved when server has been updated to 1.12.9 as well.
Sorry for the confusion / inconvenience.
