### ISSUE TITLE
Numeric keypad Enter key is ignoed

### ISSUE THREAD

**Issue by LemADEC** [anegostudios/VintageStory-Issues#488]
**Game Version:** 1.12.11
**Platform:** Windows
**Modded:** Yes, CarryCapacity

### Description
The Enter key from the numeric keypad is ignored when typing in chat.

### How to reproduce
1. Open chat
2. Type your coordinates using numeric keypad, to share with friends
3. Send the message by pressing Enter key from the numeric keypad

### Expected behavior
I would expect it to be an alternate to the Return key.

### Screenshots
n/a

### Logs
n/a

**Comment by Bloodsaw** [comment]
I guess we can consider this as an enhancement. 
Since Enter and NumpadEnter (often called "Return") are two different keys. 
Generally both keys using the same key-code (13) but most libraries does have different event-code for them, like NumpadEnter or Return. 
Binding them via key-code has the downside of not being able to bind both keys independently.
So I guess a proper way would be to add that the chat reacts on both event-codes for "Enter" and "Return".  https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=netframework-4.8

**Comment by tyronx** [comment]
I suppose it would make sense if both of them behaved the same way

**Comment by tyronx** [comment]
will work as requested in the next version

**Comment by LemADEC** [comment]
thanks!

**Comment by Bloodsaw** [comment]
Implemented in 1.12.13 (stable), can confirm this is now working as requested.
