### ISSUE TITLE
infinite saturation

### ISSUE THREAD

**Issue by djacu** [anegostudios/VintageStory-Issues#538]
I ate a partially filled bowl with a meal of red meat, bolete, and turnip and I ended up with hunger that wouldn't decrease. There is 0% saturation of protein and vegetable but the meal says it is 1% full.
![2020-05-29_19-00-13](https://user-images.githubusercontent.com/7043297/83317104-496ed280-a1df-11ea-9240-aa76a91077e1.png)

**Comment by djacu** [comment]
Restarting the client did fix the issue.

**Comment by tyronx** [comment]
Please let us know if this bug appears again, closing until then

**Comment by JapanHasRice** [comment]
I ran into this issue as well. It is triggered when you eat a meal from a bowl, only a portion of the meal is consumed, and your saturation is filled to 1500/1500. When these conditions are met, saturation will remain at 1500/1500 until the client is restarted.

---

**Game Version:** 1.14.7
**Platform:** Windows
**Modded:** No

### Description
Saturation does not deplete until client restart.

### How to reproduce
1. Create a meal in a bowl (I used hearty stew)
2. Have less than max saturation, but not be missing more than the total saturation given by the meal
3. Eat the meal
4. Saturation is restored to 1500/1500
5. The meal in a bowl is kept and the serving size is reduced
6. Saturation will no longer reduce over time

### Expected behavior
Saturation is restored, but should continue reducing over time as normal

### Screenshots

### Logs
