### ISSUE TITLE
Command line options to specify individual mods to load

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/VintageStory-Issues#608]
Currently, in order to disable a mod in development, I need to manually disable the mods I usually have installed. It would be very convenient if there was a way to specify the mods I want to load, perhaps by passing the mod ID or path to the mod, so it's not necessary to disable and enable mods.

**Comment by VeryGoodDog** [comment]
Also, this is different from the --addModPath option because it would negate the normal directories, instead of adding to them.

**Comment by copygirl** [comment]
You can specify a different `--dataPath` and I think that would mean mods from the usual folder in AppData (on Windows) would not be loaded. (You also don't share options or worlds.) Unsure if that is a complete solution to the problem but I wanted to point it out.

I think the real solution is still to have the ability to specify mods per-world rather than globally. (#4)

**Comment by VeryGoodDog** [comment]
Setting `--dataPath` did more or less what I wanted to do, and is probably better at isolating development from the normal game. Thanks
