### ISSUE TITLE
Disappearing items

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#648]
**Game Version:** v1.13, v1.14
**Platform:** Any
**Modded:** No

### Description
Multiple users report that items disappear or a client desync happens where a reload of the world restores the correct state.
Bug happens super intermittently. Please gather all available info.

### Recent reports

```
pakratt001311/10/2020
1.13.4 I double-clicked a short stack of cooling iron ingots in my inventory, and they poofed...here's a clip: https://clips.twitch.tv/HeadstrongAmazingHedgehogGrammarKing
```

```
Londor11/13/2020
pre.8 [Singleplayer] - I was chiseling , my iron chisel broke so i got to go and make a new one. I picked up a ingot of iron , placed it into the forge. Got to my Coalchest and Shift-Clicked a Stack of Coal into my Hotbar. Inventory was by then completly empty.

The coal stayed in the chest , but i had back my chisel with one "HP" :man_shrugging:  and also the ingot. So i dublicated the Ingot.

[Update] After Reloading the World, the Ingot in the Forge is gone.
```

**Comment by DArkHekRoMaNT** [comment]
I regularly see this on TOPTS when it lags. Especially if you use Shift and multiple inventories. Sometimes my items visually appear in several inventories at once. What you did before does not matter.

**Comment by unlightednetting** [comment]
Version 1.15.2, Multiplayer, 2-4 online players. I do not believe there was lag, but there may have been, as I discovered I am having a connection issue overall. This, however, should not have been a problem, as I was hosting the game on my Playing PC, using the Dedicated Server.exe

This happened with me initially with Shift Clicking Peridotite into a storage vessel. The item appears in the UI until closing the game and opening again. 

I spawned the item back in through creative, only to shift click again and have it disappear again.

For the time being, I experimented. Shift clicking ANY item at any number showed the item in the storage unit, until closing and opening it again, at which point it was missnig from both inventories. 

Left clicking and inserting via mouse did not have this issue.

For the time being, I started experimenting with which containers were affected: All of them. Which items: Any of them.
I disconnected and reconnected, still having no such luck. I closed the game entirely, and opened it again, with no such luck.

I tested in singleplayer, this was not happening. The other players were not affected, as well. I had them test with safe items such as peridodite cchunks, the item that I initially noticed the issue on

I removed my mods, and added them again, with no difference.

Eventually what happened was that I closed the entire server, and restarted my computer and router.

This has lead to me having seperate connection issues, such as the game crashing for unfulfilled heartbeat.

Changing the Server.exe to the living room computerr solved that, so I logged back in to test again.
This solved the issue for now, though it would not explain exactly what went wrong, aside from something that may have been fixed by a restart. The issue has still happened very rarely, for me, with two items disappearing in the last 3 days. One was a stack of peridotite cobblestone, I had right clicked to place them and the game refused to place them, removing the entire stack. The other time, I cannot recall, and these memories are hazy, apologies and I hope it helps.

**Comment by unlightednetting** [comment]
As an additional note, I believe I tried to Shift Click while another user was in the inventory. Despite me seeing it in the storage units, the other player could not.

**Comment by McJty** [comment]
I've never had this happen single player. I wonder if this bug is exclusive to server usage or not. Might give a hint as to what is going on

**Comment by Craluminum2413** [comment]
I'm 99% sure this only happens with servers

**Comment by linaritara** [comment]
I had multiple pieces of rough fencing (I believe both larch and pine) disappear from my inventory while playing on a server with one other person. It was an open to LAN type server, I was hosting. I was trying to set the fencing down on the ground next to a berry bush when it happened.

**Comment by VoidAngel** [comment]
Well this isnt related to desync.. so maybe not relevant, but this is what happened to me around the time of the initial 1.15 release while playing on modded multiplayer with about 12 other players (and no noticeable lag).

1) I went to go check the stock on a nearby trader. When I clicked on the trader nothing happened, no inventory, nothing. I tried to access the trader again but nothing. At that point I became distracted while talking to another player and left the trader to go help them out with chopping trees. 
2) During the tree chopping my inventory became full without me noticing. I opened my backpack inventory and quickly tried to shift click some logs from my hotbar to my backpack. Though, this wouldn't have worked anyways as my inventory was full.
3) The logs disappeared completely.
4) I tried clicking around my inventory, checking on the ground, I even relogged to check if it would come back. Nope. It was actually gone.
5) I was able to recreate the bug over and over, without fail, using different items (during that time). I had no idea where the stuff went, I just thought it was all being deleted.
6) I asked several others to try shift clicking items from their hotbar with a full inventory but no one else had the issue but me. 
7) About an hour later another player told me that they found all the items in the trader's 4 "Your offer" slots. I went over there and opened the traders inventory, and sure enough, everything that I had lost was there (and yes the inventory opened fine that time). I took the items back and closed the inventory.
8) The items stopped disappearing after that and also I've never had anything like that ever happen again.

So that just makes me wonder, are some of these shift click bugs happening because a player somehow has another inventory open that they cant see? Open, yet not open at the same time? The weird thing for me is that somehow the trader inventory stayed "open" but not visible for me even when I was very far away and even through a relog.

PS: I've also lost seeds while planting with terrible connection, but that was a while ago and to me, not a very notable event.

**Comment by kfp** [comment]
I experienced this and I think this very well could have been related to desync and possibly me unknowingly throwing items on the ground at some point. After cooking up some soybeans and scooping them up in a bowl/crock I moved 11 rusty gears 5 green gems via shift click from a chest into my hotbar, then closed the chest and opened my inventory and shift clicked them into my inventory. I then went on a short hike where i picked up some dirt and other stuff and moved some things around on the way to a trader. By the time I got to the trader my gems and RGs were gone. I tried to sell some diamonds with shift click but they were the wrong quality. Mined and picked up some other stuff on the way home to realize the diamonds were gone too.

I experienced some desync with items along the way but did not specifically notice any lag. It's possible the desynced items caused me to pick up and unwittingly drop the worthwhile stuff. 

Server, 1.15.3

**Comment by DArkHekRoMaNT** [comment]
> I had multiple pieces of rough fencing (I believe both larch and pine) disappear from my inventory while playing on a server with one other person. It was an open to LAN type server, I was hosting. I was trying to set the fencing down on the ground next to a berry bush when it happened.
I had this too, but then I found my things in one of the chests :smile:

**Comment by romeosierra131313** [comment]
When using a forge , if i light 2x ,one right after the next .For me they both appear lit , the blooms change colours the full works .When i try to pick them up the forge updates and i see one was not lit the fuel reappears as  not burnt and i get 1 hot bloom and one cold bloom . It appeared at first as disappearing blooms but further investigation have netted these findings.

**Comment by PROMETHIA-27** [comment]
I've been having many items disappear on a singleplayer world. Playing on 1.15.4 right now, and have very little idea where the items are going. I only notice they're gone later when I try to use them. Most recent item to disappear was my copper pickaxe, but I've also lost my rye seeds, tools, a stack of sticks, logs, and random other items that I usually just assumed I misremembered having. At this point I know for a fact things are disappearing, because there's no way I just misremembered having a copper pickaxe.

**Comment by CrusaderRabbit** [comment]
Had a couple issues here, shift+clicked lost 3 stacks of coal but prior to that was trying to milk ewes  then the ewe moved and player accidentally placed bucket and it disappeared. Then the player was able to reproduce the shift click bug after relog.


[player-client-main2nd.txt](https://github.com/anegostudios/VintageStory-Issues/files/6994337/player-client-main2nd.txt)
[player-client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6994296/player-client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6994297/server-main.txt)

**Comment by provet1** [comment]
I had this issue in multiplayer when my internet setup was adsl + wifi (a couple of days). With my normal setup fiber + wired, I hadn't noticed this issue. What happened for me was moving and crafting with shift-click seemed to work until I tried to place the crafted items when they instead disappeared. I put the items in a container and asked another player to pick them up but he didn't see any.

**Comment by Wreckstation** [comment]
had a bizarre variant in single player, 1.15.5. was eating extra berries to make room for a thrown copper spear and held down the right mouse button, ended up throwing the spear by accident but it vanished? i walked back spearless. since i was out of the cave i pressed x to swap the lantern from my off hand to my main hand, and the copper spear appeared in my main hand while my off hand kept the lantern(?!) Not sure what else i could have done to cause it, i was rather close to a wall when i threw the spear though, so i did not see the spear actually in the air or land, only the charging throw animation.

**Comment by gamenerd2026** [comment]
Meat stew, hearty, after eating from bowl, I ate from pot. it went in my 9th slot when it dissapeard

**Comment by tyronx** [comment]
Had this happen again on 1.16.3 in SMP, during period of bad internet connectivity. Multiple items disappeared.

In one instance a cooking pot was shift clicked into a firepit and then turnips. It seems as if the turnips overwrote the cooking pot inside the cooking slot.

The server itself was running fine and showed no perf issues through /stats

**Comment by tyronx** [comment]
> Had this happen again on 1.16.3 in SMP, during period of bad internet connectivity. Multiple items disappeared.
> 
> In one instance a cooking pot was shift clicked into a firepit and then turnips. It seems as if the turnips overwrote the cooking pot inside the cooking slot.
> 
> The server itself was running fine and showed no perf issues through /stats

We had carrycapacity installed. We were able to reliably reproduce item disappearence using mechanics of that mod.

**Comment by copygirl** [comment]
Closing as invalid due to being a bug in a mod, not the game.

(I [released a version of CarryCapacity](https://github.com/copygirl/CarryCapacity/releases) that hopefully addresses this issue.)

**Comment by copygirl** [comment]
I was too eager to close this. After being told and looking again, this appears to also happen in non-modded environments.
Apologies. Still, if you were experiencing this with CarryCapacity in version 0.6.4 or before, it's a likely culprit.

**Comment by tyronx** [comment]
Yea, there seem to be several causes

**Comment by copygirl** [comment]
(Meant to reopen it when I commented yesterday.)

**Comment by goldkin** [comment]
This is assuredly not the only source of this bug, but we were able to reproduce this on our multiplayer instance (modded, but see below) and wanted to share our observation and hypothesis on what went wrong.

Server spec:
* Game version 1.16.4
* Mod ids (as in https://mods.vintagestory.at/show/mod/#): 17, 28, 53, 78, 280, 321, 463, 654, 1061, 1238, 1373, and 1627, using the latest versions as of 2022-04-14
* Settings are mostly vanilla Survival, with some minor alterations done via /serverconfig and /worldconfig

We started to observe some of the anecdotal stacking bugs described upthread after one of our players had a client crash. Base game items (tested with grass) stacked just fine in bags, but subsequent pickups would land in the hotbar instead of in their stacks in their bag. Subsequent attempts to join the bag inventory stack with the main hotbar stack would overwrite whatever was on the hotbar, and vice versa, reliably, only for this player, and would not be written back to the server.

Attempts to fix this that did not work:
* Rebooting the server (eg, ./server.sh restart)
* Relogging the player (this would synchronize state between their client and the server, but the stacking bug persisted)
* Clearing the player inventory (via /clrplrinv)
* Killing or otherwise respawning the character (with drop on death disabled, so this would not have impacted their inventory contents)

What did fix it:
* Creating a base multiplayer world that was unmodded at the same server IP, connecting their client to that version of the server

We verified this cleared the inventory stacking behavior, which initially made us think that mods were at issue.

However, when we subsequently brought the original server back up and had our player connect to it, their issues were resolved. Note that this was an independent install of the server (for a different Linux user on the same system), so there would not have been cross-pollination of database settings between installs.

We think that this somehow fixed an issue in their client, and while we were not able to test this, I bet reinstalling the game on their end would have also fixed it.

This makes me think that what happened is a sanity check needs to be added for received item and/or block ids at the client side, and that the cause in this case was corrupt or uninitialized data being written back to their client database file(s) when their client crashed.

---

I doubt this is the only way in which this issue reproduces itself, and from the perspective of how the game is programmed, I only vaguely know what I'm talking about here cobbled together from our two neophyte server admins. But hopefully this offers breadcrumbs to help track down the issue.

**Comment by goldkin** [comment]
Additionally, one of our other players reported disappearing items as they moved a stack and then immediately logged out, but that probably has a more straightforward explanation (that the transaction had not yet been written back to the server as they logged out). Also worth noting here, but not a related repro of this issue.

**Comment by tyronx** [comment]
haven't seen any new reports on this, assuming to be fixed or no longer a major issue
