### ISSUE TITLE
Graphics smear then crash almost every time I play Vintage Story. Must restart PC or it freezes up and hard slam.

### ISSUE THREAD

**Issue by Deltaclimber** [anegostudios/VintageStory-Issues#683]
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment]
Please actually fill out the provided bug report template. Since this is a graphics related bug, also provide the graphics card you use and attach the `client-main.txt` after such a crash has occurred. This could be an issue with your graphics driver (see if you can update it) or the hardware itself.

**Comment by Craluminum2413** [comment]
There is no additional useful information, and the author didn't answer for a very long time. Seems it is worth to close it
