### ISSUE TITLE
Smithing metal reclamation

### ISSUE THREAD

**Issue by CalligoMiles** [anegostudios/VintageStory-Issues#754]
It is fairly obvious that a lot of tools really don't require a full 100 units of metal - knives, hoes and prospecting picks in particular. Yet every single one of those requires a full ingot and over half of the smithing process ends up being just destroying valuable metal.

I understand that this might be more practical design- and mechanic-wise, but I think it could be elegantly solved by using the voxel 'counter' of pottery and the break-off mechanism of knapping - basically, if you split off multiple voxels that are attached to the 'completed' tool head by a single voxel, you get some material back based on the amount of voxels you managed to remove without splitting them. Maybe directly the % of the ingot you saved, maybe a diminished amount to keep it balanced - and of course the shavings/fragments would need to be melted once more to be of any use.

In my opinion this would serve nicely to both reward smithing skill, and to allow you to stretch your resources early on at the expense of more work.

**Comment by Harlekin13** [comment]
similar topic like #691

**Comment by CalligoMiles** [comment]
Really not quite the same topic.

And that mod is pretty close, but makes it a bit too easy in my opinion. And either way, the mod existing isn't exactly a good reason not to include something like it in the base game at some point.

**Comment by Harlekin13** [comment]
i never said it's the same topic, it's just similar, in the way that both topics try to improve metal working, and further down, they could become exclusive (?) to each other, something i want to prevent, therefore mentioning it so that there is a two-way connection on github and neither gets lost when it comes to implementation.

And i didn't mean "just use the mod instead no implementation needed", just that there is already a mod that does something similar and using the mods way might be a rather easy way to implement it in vanilla and for the time being you could use the mod until it's implemented.

**Comment by Craluminum2413** [comment]
@copygirl It was a suggestion and still not closed
