### ISSUE TITLE
Controls can be assigned to "escape", making it impossible to get back to the controls menu

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#78]
What it should do instead when you press escape is either cancel the controls reassignment or disable the hotkey. Opening the menu or navigating it should never not be possible.

**Comment by tyronx** [comment]
Actually, something else is happening here. Hitting escape while assigning a control closes the dialog without cancelling the active capture or something weird like that. 

Fixed it so that the escape key is again properly forwarded to the controls gui component, probably broke something else doing so. Hitting esc will now cancel the reassignment in 1.5.4
