### ISSUE TITLE
Fence gate collision box doesn't open with gate.

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#782]
Fence gate collision box doesn't open with gate. So when closing gate I should click on "closed gate" collision box instead of opened gate. It's unintiutive. I found myself clicking on not working open gate part every time I want to close gate.

**Comment by Th3Dilli** [comment]
thank you for reporting

it seems this has been "fixed" already for some time
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31390939/6af6f54b-b3b2-4155-938c-3cb4b9d3e6a1)

there is some drawback to it, since due to how the engine handles selecting and highlighting the current block a hitbox/selection box can not extend its own block (mostly for performance reasons). So even if we increase the selection box seen in the image it will not allow you to select it when that part of the selection box would be in another block already
