### ISSUE TITLE
Windows client 1.14.7 is able to connect to server 1.14.8

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#799]
**Game Version:** 1.14.8
**Platform:** CLients windows, server linux
**Modded:** Yes, Medieval Expansion 3.3.3, Rope bridges 1.0.6 

### Description
Windows client 1.14.7 is able to connect to server 1.14.8. Is it a feature or a bug? 
I just updated our server to the 1.14.8 and run it and I noticed that my friend has been able to connect to the server with client 1.14.7.

**Comment by copygirl** [comment]
When there are no content additions or incompatibilities between versions that would otherwise make it impossible to connect, the developers keep the "network version" the same, allowing servers and clients of different versions to connect to one another. Since 1.14.8 has been mostly fixes that don't affect gameplay, this is the case with this patch.
