### ISSUE TITLE
Please NO new map generator i.e. map reset !!!!

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#880]
Hell Tyron and dev team,

I can complain on some features, or bugs. I can suggest some new features. But all this isn't so important because I can more or less copy with all.
BUT I'd like to emphasize one very very important issue concerning VS:

Every map generator reset/change caused BIG problems with map continuity (new terrain doesn't fit old one) in Minecraft. PLEASE PLEASE avoid this !!!!!! We'd like to keep our server progress (map, buildings, etc...) a we don't want to spoil our map by terrain generator reset. So if you'll make some change please keep old generator as an option or introduce some mechnaism so the old terrain seamlessly continue to new one (although I think this would be very tough to do maybe impossible).

**Comment by copygirl** [comment]
Vintage Story's world generation works much differently than Minecraft, and is arguably more advanced and complete. I doubt the overall algorithm will change, so there would never be hard cuts in the world due to the overall shape changing. There are no biomes either, plants simply generate depending on factors like local temperature, rainfall, forest density, etc. When additional content is put into the game, it will simply appear in newly generated terrain.

That doesn't mean that there's never going to be cause for having to do a hard reset on a world, but I believe drastic changes to the world generation won't be the reason.

**Comment by petrnowak** [comment]
Perfect! I love Vintage Story !!!

**Comment by tyronx** [comment]
What copygirl wrote. If we do major worldgen changes that could cause chunk borders we usually keep the old code around for old worlds to avoid such issues.
