### ISSUE TITLE
Don't load universal mods on the client side if the server is not loading them

### ISSUE THREAD

**Issue by tyronx** [anegostudios/VintageStory-Issues#92]

**Comment by ApacheTech** [comment]
I disagree with this being a bug.

Take "Campaign Cartographer" as a case study. With this mod, the vast majority of the mod only runs on the client. It can be run as a Client-Only mod when playing in any world, single-player, or multi-player. However, it is a Universal Mod. It can be installed on a Server. When it is, any Clients that also have it installed will have extra functionality because it's installed on the server. Currently this only really includes the ability to send GPS coordinates to other clients, as a Private Message in game, rather than publicly in chat, but there is a lot more functionality that could be added as well.

If this change is implemented, it would irrecoverably break mods like this, where functionality is not dependent on the server, but can be enhanced by it. In ModInfo, I have `RequiredOnClient` and `RequiredOnServer` both set to false.

```json
{
  "type": "Code",
  "name": "Campaign Cartographer",
  "modId": "campaigncartographer",
  "side": "Universal",
  "requiredOnClient": false,
  "requiredOnServer": false
}
```

The server shouldn't care if the mod is installed on the client, and the client shouldn't care if the mod is installed on the server... right up to the point where that functionality is needed. This is done by checking whether the Client network channel is connected or not. If it's not, the mod isn't installed on the server, and the user is given feedback to say that the feature is unavailable, and to ask their server admin to install the mod on the server to use the feature. 

```csharp
    if (_clientChannel is not null && !_clientChannel.Connected)
    {
        _capi.ShowChatMessage(LangEx.Error("mod-not-installed-on-server"));
        _capi.ShowChatMessage(LangEx.Message("plug-mod-to-server-admins"));
        return;
    }
```

If this is implemented, could it be limited only to Universal mods that stipulate `"requiredOnClient": true`?

https://github.com/ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer

**Comment by tyronx** [comment]
I think this is outdated and no longer required, so closing.
