### ISSUE TITLE
The leaves become transparent when you look at them through the grass

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#921]
**Game Version:** 1.15.0-pre.11
**Platform:** Windows
**Modded:** No

### Description
The leaves become transparent when you look at them through the grass, if there is a visible sky behind

### How to reproduce
1. Create a superflat world for best results (this bug requires sky background).
2. Build a wall of leaves, for example, three blocks wide and any length.
3. Within a few blocks from the wall of leaves place the soil three blocks wide (make it as length as leaves wall for best results) and put very tall grass (or flowers) on them.
4. Build something (not using leaves, glass or any transparent blocks) behind a wall of leaves, so that you can look at it through the grass you placed.
5. Step back 30-50 blocks from the grass while looking at leaves wall through the grass.
6. The leaves become transparent and you can see anything behind them, if there is a sky in their background.

### Expected behavior
Leaves don't become transparent

### Screenshots
![2021-05-28_14-53-25](https://user-images.githubusercontent.com/69315569/119981256-144db980-bfc6-11eb-868b-8f9c7c636c22.png)
![2021-05-28_14-53-44](https://user-images.githubusercontent.com/69315569/119981259-157ee680-bfc6-11eb-89e9-c3179b412f46.png)
![2021-06-13_15-01-59](https://user-images.githubusercontent.com/69315569/121806404-68100200-cc58-11eb-933a-61943b088da6.png)
![image](https://user-images.githubusercontent.com/69315569/131385125-3ca935f0-1dcd-4aa2-879f-9d8faa714218.png)

### Videos
https://user-images.githubusercontent.com/69315569/124107619-1811a780-da6e-11eb-864b-4463727a11a9.mp4

https://user-images.githubusercontent.com/69315569/126048030-b4e11f4c-cbfc-40b6-a764-fc2b727a048b.mp4

**Comment by copygirl** [comment]
Could that have to do with mipmapping involving partially transparent textures?

**Comment by sirStroam** [comment]
I'm unable to reproduce this in 1.15 pre 11. Is this still a thing?

**Comment by copygirl** [comment]
![image](https://user-images.githubusercontent.com/272586/124093004-ba726080-da57-11eb-86f0-1e9008d98706.png)
In this image you can see two quads of different plants that look like the fog color. Not sure if this is the same issue however.
(Tested in 1.15.0-pre.3 because that's what I had installed.)

**Comment by Craluminum2413** [comment]
This bug is still relevant. It cannot fix itself.

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/124107619-1811a780-da6e-11eb-864b-4463727a11a9.mp4

**Comment by Craluminum2413** [comment]
Also. Look at the particles. The first is water, the second are crystals

https://user-images.githubusercontent.com/69315569/124774908-d8076480-df46-11eb-8e0c-43db6cde4b6f.mp4

**Comment by sirStroam** [comment]
I can't see anything. It looks like you are just looking at the night sky

**Comment by Craluminum2413** [comment]
> I can't see anything. It looks like you are just looking at the night sky

How can you not notice water or a bunch of crystals in the torch particles?

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/126048030-b4e11f4c-cbfc-40b6-a764-fc2b727a048b.mp4

**Comment by Craluminum2413** [comment]
https://user-images.githubusercontent.com/69315569/126048435-4e1099f5-8d3f-473e-ba3f-8cc567b81e40.mp4

**Comment by Asmidus** [comment]
This is still an issue, though even more obvious now with oceans in 1.18 previews, since water doesn't render behind grass either (in the same way that the leaves don't in the original bug report). The grey outline of this grass is just the skybox because the water isn't rendered immediately behind it.
![image](https://user-images.githubusercontent.com/37638316/226788731-8fd63306-974e-443b-8e56-50709941bcf4.png)

**Comment by noelle-lavenza** [comment]
**Changing the renderpass property of tall grass to `OpaqueNoCull` seems to have fixed it with, as far as I can tell, no side effects.** 
Before:
![image](https://i.imgur.com/DVdbEyU.png)
After:
![image](https://i.imgur.com/MBn1yGL.png)

Checking in RenderDoc with transparent pixels shown with a red backdrop reveals the actual issue:
![image](https://i.imgur.com/iHqQ8Ge.png)
The sky pixels in the grass blocks affected by the issue *are not actually transparent,* instead being a copy of the background.

For some context, the order of rendering passes is, as far as I can tell:
- 0: Opaque
- 5: Topsoil
- 2: BlendNoCull
- 1: OpaqueNoCull
- 4: Liquid
- 3: Transparent
- 6: Meta

Tall grass has `renderpass: "BlendNoCull"`. It appears that because leaves render on a later pass, `OpaqueNoCull`, leaves behind tall grass will be occluded by the non-transparent sky pixels.

Setting it to `Transparent` also worked, but introduced a new artifact when grass textures overlapped at different distances.

When set to `Opaque`, aside from the obvious issue of backface culling, the issue was much clearer to see and also ignored the terrain entirely (due to being on the same RenderPass). It's particularly bad at an almost parallel angle to the affected part of the grass model, and at longer distances. This seemed to me to indicate that the underlying issue is with the billboarding code in the grass shader, but no changes I made to the shader locally seemed to help.
![image](https://i.imgur.com/B5h7FU3.png)

For completeness' sake, setting it to `Meta` and rendering meta blocks also fixed the issue nearly identically to the `OpaqueNoCull` one, implying it's a render order problem. Setting it to `Liquid` caused terrible artifacting.

As best as I can tell, the reason instanced plants fixed it was because they're drawn in a separate/bespoke rendering step (probably the reason it was removed, if I had to guess) after the OpaqueNoCull step, meaning they don't draw over leaves that are closer to the camera. However, they likely still had the sky texture artifacts, just in a way that didn't make it look weird.

I don't think this fixes the texture artifacts, but at least they're not visible under normal conditions anymore.

**Comment by tyronx** [comment]
hey, much appreciate the effort you put into this. There is a visual difference, but it almost seems to look better. I can switch that over to OpaqueNoCull 👌 

It's possible that i need to revert this again though. I have a vague memory that it was set to blend for a very good reason.

Will be in rc.3

**Comment by Craluminum2413** [comment]
Glad it finally fixed! 🥰

**Comment by Craluminum2413** [comment]
@tyronx  What about particles from here? Are they fixed too? Should I open separate issue for particles?
https://github.com/anegostudios/VintageStory-Issues/issues/921#issuecomment-875642577
https://github.com/anegostudios/VintageStory-Issues/issues/921#issuecomment-881954740

**Comment by tyronx** [comment]
oh yea, thats a separate issue and likely has no fix unless transparent rendering is rewritten to a very different system

**Comment by kousakak** [comment]
Not fixed in fact,still exist in 1.18.4...
![screenshot](https://github.com/anegostudios/VintageStory-Issues/assets/60339803/b5dad3b5-ab7b-49ae-86ca-e01f39674500)

**Comment by tyronx** [comment]
oh, probably red top grass is not in the right render pass

**Comment by tyronx** [comment]
hm, no, it is actually

**Comment by noelle-lavenza** [comment]
That screenshot seems to show it affecting liquids, which use a different renderpass than leaves, I think. It could be yet another ordering problem.

**Comment by Asmidus** [comment]
I think I was able to fix this locally by editing the shape files the affected grass and flowers were using and removing the renderpass lines. The renderpass in the shape overrode the renderpass set in the object file or something, so even though it looked like it should be OpaqueNoCull it wasn't in practice 

I'm operating on memory from a few months ago but I believe this was the case.

**Comment by Craluminum2413** [comment]
Can't reproduce in 1.20 anymore

**Comment by noelle-lavenza** [comment]
> Can't reproduce in 1.20 anymore, probably was fixed in earlier versions

did you make sure to check red top grass against liquids?

**Comment by Craluminum2413** [comment]
@noelle-lavenza Yes. Did you check it yourself too?
