### ISSUE TITLE
Rope : cannot craft from vines collected on kapok tree

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#954]
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No

### Description
Cannot craft a rope from wild vines collected on kapok. Either those falling down from the leaves than those sticked to the trunk.

Another thing : a kapok log give 3 firewoods where the other woods give 4, but I don't know if this is on purpose or not.

**Comment by Craluminum2413** [comment]
3 firewood from kapok log is intended thing

**Comment by Saricane** [comment]
I looked for information about this before reporting it, but found nothing. Is this particularity documented somewhere ?

**Comment by Craluminum2413** [comment]
#235 Tyron said so

**Comment by Craluminum2413** [comment]
Rope has 4 different wild vines in its recipe, this is very strange. Why we **cannot see item's code in the handbook**? It's very annoying.

I found four variants of wild 

vine:
`wildvine-section-north`, `wildvine-section-east`, `wildvine-section-south`, `wildvine-section-west`.

Also four their tropical variants (only they cannot be used in recipes):
`wildvine-tropical-section-north`, `wildvine-tropical-section-east`, `wildvine-tropical-section-south`, `wildvine-tropical-section-west`.

In the video, it blinked 4 times because of that!

https://user-images.githubusercontent.com/69315569/121928383-c1575e80-cd48-11eb-8b6f-d078fbebce80.mp4

**Comment by Craluminum2413** [comment]
I think issue can be renamed to "Cannot craft rope from tropical wild vines"

**Comment by radfast** [comment]
Both issues (inability to craft, and the 4 x repetition of the recipe) are fixed in next build.  Whether that is pre12 or rc1, who knows ...

The fix is that both vine types in the world (standard and kapok) will both now drop a `wildvine-section-north` item, and that is the only type which needs a recipe.
