### ISSUE TITLE
Reverse movement

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#976]
When I type ".movespeed -1", then all my movements are reversed. Right is left, up is down, etc. Is it intentional?
Also ".movespeed 0" stops me completely

**Comment by copygirl** [comment]
The value is multiplicative, so 0 should stop you completely. Negative values could be disallowed but otherwise I don't see a reason why this is a big issue.

As for the technical explanation, movement is a vector, for example `[1, 0]` could be to the right, `[-1, 0]` to the left and `[0, 1]` could be forward. `[1, 1]` would be moving diagonally. If you multiply the movement vector by the movespeed value, you get the final speed. `[1, 0] * 2` is `[2, 0]`. And when you set movespeed to -1 you get `[1, 0] * -1` which is `[-1, 0]`. So right becomes left.
